apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: blong-kustomize
    app.kubernetes.io/name: blong-suite
    app.kubernetes.io/part-of: blong-suite
    app.kubernetes.io/version: 1.13.0
    blong.feasible.one/spec-hash: e487e03e20053963
  name: blong-operator
  namespace: blong-suite
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: blong-operator
subjects:
  - kind: ServiceAccount
    name: blong-operator
    namespace: blong-system
