apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: blong-kustomize
    app.kubernetes.io/name: blong-operator
    app.kubernetes.io/part-of: blong-operator
    app.kubernetes.io/version: 0.1.0
    blong.feasible.one/spec-hash: 1f9786a2424fcc5f
  name: blong-system
