import {schema} from '@feasibleone/blong';

export default schema(async ({lib: {type}}) => ({
    coral: type.Object({
        coralId: type.increment(),
        coralName: type.stringNotNull(),
        familyId: type.integerNotNull(),
        habitatId: type.integerNull(),
        coralType: type.stringNull({maxLength: 10}),
        maxDepth: type.integerNull(),
        colorPattern: type.stringNull(),
        conservationStatus: type.stringNull({maxLength: 2}),
        isEndangered: type.booleanNull(),
        discoveryDate: type.dateNull(),
        coralDescription: type.stringNull(),
        createdAt: type.dateTimeNull(),
        createdBy: type.integerNull(),
        updatedAt: type.dateTimeNull(),
        updatedBy: type.integerNull(),
        isActive: type.booleanNull(),
    }),
    family: type.Object({
        familyId: type.increment(),
        familyName: type.stringNotNull(),
        parentFamilyId: type.integerNull(),
        order: type.stringNotNull(),
        class: type.stringNotNull(),
        familyDescription: type.stringNull(),
        createdAt: type.dateTimeNull(),
        createdBy: type.integerNull(),
        updatedAt: type.dateTimeNull(),
        updatedBy: type.integerNull(),
        isActive: type.booleanNull(),
    }),
    habitat: type.Object({
        habitatId: type.increment(),
        habitatName: type.stringNotNull(),
        habitatType: type.stringNotNull({maxLength: 20}),
        zone: type.stringNotNull({maxLength: 20}),
        oceanZone: type.stringNotNull({maxLength: 20}),
        region: type.stringNotNull(),
        minDepth: type.integerNull(),
        maxDepth: type.integerNull(),
        waterTempMin: type.integerNull(),
        waterTempMax: type.integerNull(),
        latitude: type.numberNull(),
        longitude: type.numberNull(),
        protectionStatus: type.booleanNull(),
        habitatDescription: type.stringNull(),
        createdAt: type.dateTimeNull(),
        createdBy: type.integerNull(),
        updatedAt: type.dateTimeNull(),
        updatedBy: type.integerNull(),
        isActive: type.booleanNull(),
    }),
    species: type.Object({
        speciesId: type.increment(),
        speciesName: type.stringNotNull(),
        scientificName: type.stringNotNull(),
        genus: type.stringNotNull(),
        species: type.stringNotNull(),
        familyId: type.integerNotNull(),
        conservationStatus: type.stringNotNull({maxLength: 2}),
        bodyLength: type.numberNull(),
        lifespan: type.integerNull(),
        diet: type.stringNull({maxLength: 20}),
        isEndangered: type.booleanNull(),
        speciesDescription: type.stringNull(),
        createdAt: type.dateTimeNull(),
        createdBy: type.integerNull(),
        updatedAt: type.dateTimeNull(),
        updatedBy: type.integerNull(),
        isActive: type.booleanNull(),
    }),
}));
