version: "0.2"
language: en-GB
words:
  - ACMR
  - Acropora
  - Acroporidae
  - adaptername
  - Alcyonacea
  - allurerc
  - Ambrym
  - amodio
  - Amphiprion
  - analyzed
  - Analyzed
  - Analyzes
  - Anders
  - Anthoathecata
  - Anthozoa
  - Antipatharia
  - Antipathidae
  - apidevtools
  - APIV
  - apos
  - approle
  - APTRA
  - arqc
  - Arqc
  - ARQC
  - ARYZ
  - autodocs
  - azooxanthellate
  - behaviour
  - binhex
  - Bislama
  - bitsyntax
  - Български
  - Активен
  - език
  - запазен
  - Имейл
  - Неактивен
  - Нова
  - новата
  - Няма
  - Отписване
  - Паролата
  - Паролите
  - парола
  - Потвърди
  - Предпочитан
  - присвоени
  - Профил
  - Профилът
  - роли
  - Роли
  - Смяна
  - смяна
  - сменена
  - Собствено
  - съвпадат
  - Текуща
  - Фамилия
  - blong
  - cacache
  - Cacache
  - capath
  - centered
  - cervicornis
  - cfg
  - Chelonia
  - cirratum
  - cleanup
  - Cleanup
  - Clownfish
  - clusterrole
  - clusterrolebinding
  - clusterrolebindings
  - clusterroles
  - codegen
  - commitish
  - Commitish
  - configmap
  - confirmdialog
  - confirmpopup
  - crockford
  - cutoff
  - daemonset
  - dapr
  - darkorange
  - datatable
  - datetime
  - dbaeumer
  - dedup
  - deepwater
  - DELEGATOR
  - Dendrophylliidae
  - destructures
  - detritivore
  - Detritivore
  - devrc
  - dfsp
  - DFSP
  - DFSPs
  - dialog
  - Diebold
  - dismissable
  - dont
  - drpp
  - dukpt
  - ECDH
  - EEST
  - elkhorn
  - Elkhorn
  - endregion
  - ERRORRELEASEJOBTRIGGER
  - errorreleasjobtrigger
  - ESOCKETTIMEDOUT
  - fallbacks
  - fastify
  - Faviidae
  - feasibleone
  - franca
  - fspiop
  - FSPIOP
  - FULLTEXT
  - Fungiidae
  - GBIF
  - Ginglymostoma
  - gogo
  - googleusercontent
  - Gorgoniidae
  - hdel
  - Hejlsberg
  - hepatus
  - hget
  - hgetall
  - hincrby
  - hset
  - Hydrozoa
  - idempotently
  - Indo
  - infitx
  - ingressclass
  - INOUT
  - inputmask
  - inputnumber
  - inputtext
  - inputtextarea
  - ioredis
  - ivac
  - jobtriger
  - jwks
  - kalinkrustev
  - keyblock
  - knex
  - kopi
  - kubeconfig
  - kustomization
  - lightgreen
  - Liquibase
  - LONGTEXT
  - Mandarinfish
  - mdns
  - mediumint
  - MEDIUMINT
  - MEDIUMTEXT
  - mesophotic
  - Mesophotic
  - meterprobe
  - Milleporidae
  - Millis
  - Millisec
  - mkac
  - mlek
  - mlsk
  - mocktime
  - mojaloop
  - Mojaloop
  - MPVV
  - MSISDN
  - mtid
  - mydas
  - nematocysts
  - networkpolicies
  - nosniff
  - npmjs
  - nscfg
  - ntlm
  - Ntlm
  - ocellaris
  - oidc
  - onprem
  - OpenAPIV2
  - OpenAPIV3_1
  - overlaypanel
  - panelmenu
  - paperclip
  - Paracanthurus
  - parentspanid
  - payeefsp
  - payerfsp
  - payshield
  - payshieldport
  - payshieldsim
  - persistentvolume
  - persistentvolumeclaim
  - persistentvolumeclaims
  - persistentvolumes
  - pino
  - pkce
  - pnpmfile
  - primefaces
  - primeflex
  - primeicons
  - primelocale
  - primereact
  - priorityclass
  - Proc
  - processinfo
  - progressspinner
  - Pterois
  - quasis
  - quot
  - rdkafka
  - realmname
  - realmnameitemlistactive
  - Redis
  - Redux
  - refetches
  - reflow
  - regen
  - releasejobtrigger
  - releasjobtrigger
  - reorderable
  - replicaset
  - replicasets
  - resequencer
  - Resequencer
  - restfs
  - Rndi
  - rolebinding
  - rolebindings
  - romeovs
  - roundtrip
  - Roundtrip
  - rushstack
  - sasl
  - savepoint
  - Scleractinia
  - seagrass
  - Seagrass
  - selectbutton
  - SEPA
  - serialisable
  - Siderastreidae
  - singularize
  - Singularize
  - SMPP
  - softwaregroup
  - spanid
  - splendidus
  - sqlitemadd
  - sqlitemlistactive
  - staghorn
  - Staghorn
  - statefulset
  - statefulsets
  - statelessly
  - storageclass
  - surgeonfish
  - Surgeonfish
  - svar
  - Synchiropus
  - tabmenu
  - tabmenuitem
  - tabview
  - tapjs
  - tinyint
  - TINYINT
  - TINYTEXT
  - toggleable
  - topo
  - totp
  - traceid
  - treenode
  - treeselect
  - treetable
  - typebox
  - ulidx
  - unannounce
  - ungroup
  - unixtime
  - unrole
  - unstate
  - Upserted
  - userinfo
  - userpass
  - varbinary
  - VARCHAR
  - vars
  - vitest
  - volitans
  - Voxer
  - webcamera
  - WHATWG
  - worldtimeapi
  - xyflow
  - YHHHHCC
  - ZCMK
  - zoomin
  - Zustand
  - биология
  - Видове
  - График
  - Група
  - Данни
  - динамичен
  - задължително
  - Запази
  - морска
  - Описание
  - Организация
  - Отказ
  - открити
  - Портал
  - Потребител
  - Права
  - Продукт
  - резултати
  - Роля
  - Сметка
  - Справки
  - статичен
  - Табло
  - тест
ignorePaths:
  - package-lock.json
  - node_modules
  - .git
  - pnpm-lock.yaml
  - rush.json
  - "**/*.json"
  - common/temp/**
  - core/**/~.schema.ts
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.play.ts"
  - "**/dist/**"
  - "**/storybook-static/**"
  - "**/allure-results/**"
  - "**/.playwright/**"
