/**
 * scripts/lib/checks.ts — what a deployed suite has to answer for, after the tree is applied.
 *
 * The asserts of the shell runbook it replaces, one function per claim, each reading the cluster back
 * rather than restating what was written. That distinction is the whole point of the file: an apply
 * that succeeded says the API accepted a document, and a deployment that works says the process
 * reached its tables, the portal serves a page, and the answer a caller gets carries no private key.
 *
 * Every failure is a `fail` and every inconclusive answer is a `warn`, in the proportions the shell
 * settled on after each of them had a false positive: a missing bundle is a warning because the
 * artifact may legitimately carry none, while a login answer with a private key in it is the one thing
 * that fails a run outright.
 */
import {existsSync} from 'node:fs';
import {spawn} from 'node:child_process';

import {serviceNames} from './artifacts.ts';
import {
    execInPod,
    getField,
    getJson,
    objectExists,
    podHasNode,
    portAnswers,
    portForward,
    readyPodName,
    type IPortForward,
} from './cluster.ts';
import {fail, waitFor, type IStepIo} from './exec.ts';
import {
    pageAnswer,
    privateKeyFields,
    tokenAnswer,
    upgradeArguments,
    validationRefusal,
} from './rules.ts';
import {servicesNamespaceOf} from './trees.ts';

/** The release step, which is a Job: a deployed process runs `release`, and the schema is beside it. */
export const migrationStepRan = async (
    {namespace, timeoutSeconds = 600}: {namespace: string; timeoutSeconds?: number},
    io: IStepIo,
): Promise<void> => {
    const listed = await io.capture('kubectl', ['-n', namespace, 'get', 'jobs', '-o', 'name'], {
        allowFailure: true,
    });
    const job = listed
        .split('\n')
        .map(line => line.trim())
        .filter(line => line.includes('migrate'))[0];
    if (!job) fail('the tree carries no migration Job, so nothing created the schema');
    // What the Job *runs* is checked as well as that it ran: a tree regenerated by hand can carry the
    // attempt an older generator wrote, and the shape that shipped once lost the deployment's config
    // because a positional followed a flag (F-414).
    const args = (
        await getField({
            namespace,
            resource: job,
            jsonPath: '{.spec.template.spec.containers[0].args[*]}',
        }, io)
    )
        .split(/\s+/)
        .filter(Boolean);
    const wrong = upgradeArguments(args);
    if (wrong) fail(wrong);
    await io.run('kubectl', [
        '-n',
        namespace,
        'wait',
        `--for=condition=complete`,
        job,
        `--timeout=${timeoutSeconds}s`,
    ]);
    io.log(`${job} completed`);
};

/**
 * No released process renders a `semlog://` reference.
 *
 * The stores behind a reference come from the merged config, and a deployment's own rc file can
 * configure them for a process whose intent says not to render one — which is how a released pod
 * printed `config: semlog://p/<id>` for a payload nobody reads from that stream (T-243). Checked on
 * every running container of the suite, because the platforms differ in which logger they pick.
 */
export const noSemlogReference = async (
    {namespace, tail = 1000}: {namespace: string; tail?: number},
    io: IStepIo,
): Promise<void> => {
    const listed = await io.capture('kubectl', ['-n', namespace, 'get', 'pods', '-o', 'name'], {
        allowFailure: true,
    });
    let references = 0;
    for (const pod of listed
        .split('\n')
        .map(line => line.trim())
        .filter(Boolean)
        .filter(line => !line.includes('/cache-'))) {
        const logs = await io.capture(
            'kubectl',
            ['-n', namespace, 'logs', pod, '--all-containers', `--tail=${tail}`],
            {allowFailure: true},
        );
        const count = logs.split('\n').filter(line => line.includes('semlog://')).length;
        if (count) {
            io.warn(`${pod} printed ${count} semlog reference(s)`);
            references += count;
        }
    }
    if (references) fail('a released process printed a semlog reference');
    io.log('no container printed a semlog reference');
};

/** Which node each pod landed on — the cheapest way to see that a two-node cluster is really two. */
export const podsOnNodesReport = async (
    {namespace}: {namespace: string},
    io: IStepIo,
): Promise<void> => {
    const listed = await io.capture('kubectl', [
        '-n',
        namespace,
        'get',
        'pods',
        '-o',
        'custom-columns=POD:.metadata.name,NODE:.spec.nodeName,STATUS:.status.phase',
    ]);
    io.log(listed.trimEnd());
};

/** The alias a realm's config dials, as the cluster holds it. */
export const externalNameAliasReport = async (
    {namespace, name = 'db'}: {namespace: string; name?: string},
    io: IStepIo,
): Promise<void> => {
    const type = await getField(
        {namespace, resource: `service/${name}`, jsonPath: '{.spec.type}', optional: true},
        io,
    );
    const external = await getField(
        {namespace, resource: `service/${name}`, jsonPath: '{.spec.externalName}', optional: true},
        io,
    );
    io.log(`${type} ${external}`);
};

/**
 * The services a deployment brought with it: a workload, a claim, an alias, and credentials.
 *
 * The unit tests pin the objects the generator writes; nothing but a cluster shows that one of them
 * starts, and the alias is the half a realm's config depends on — it keeps naming the service rather
 * than a host. So each service is waited for, its claim is waited to bind, its alias is compared with
 * the address it has to answer, and the alias is dialled from a pod of the suite in the suite's
 * namespace, which is where a deployment's process runs.
 */
export const backingServicesCheck = async (
    {namespace, tree, serviceOff}: {namespace: string; tree: string; serviceOff?: string},
    io: IStepIo,
): Promise<void> => {
    if (serviceOff) {
        // A service the deployment switched off leaves no trace in the tree it asked for: no
        // workload, no claim, no alias and no namespace.
        for (const leftover of [`services/${serviceOff}`, `external-services/${serviceOff}.yaml`]) {
            if (existsSync(`${tree}/${leftover}`)) {
                fail(`the tree still carries ${leftover}`);
            }
        }
        io.log(`the tree carries nothing of ${serviceOff}: the switch removed it`);
        // And the objects an earlier pass wrote into the suite's namespace are gone with it, the
        // credentials copy among them: a Secret left behind is a password a rotation never reaches,
        // while the workload's own copy in the services namespace is what stays (D-461, D-462).
        if (await objectExists({namespace, resource: `secret/${serviceOff}-credentials`}, io)) {
            fail(`the credentials copy survived the switch in ${namespace}`);
        }
        io.log('and the pass removed the credentials copy it wrote there, while the workload kept its own');
    }
    const servicesNamespace = servicesNamespaceOf({tree, suiteNamespace: namespace});
    if (!servicesNamespace) {
        io.log('the tree carries no service namespace — no service is left to bring');
        return;
    }
    io.log(`namespace ${servicesNamespace}`);
    for (const name of serviceNames(tree)) {
        await io.run('kubectl', [
            '-n',
            servicesNamespace,
            'rollout',
            'status',
            `deployment/${name}`,
            '--timeout=300s',
        ]);
        if (await objectExists({namespace: servicesNamespace, resource: `pvc/${name}-data`}, io)) {
            await io.run('kubectl', [
                '-n',
                servicesNamespace,
                'wait',
                '--for=jsonpath={.status.phase}=Bound',
                `pvc/${name}-data`,
                '--timeout=180s',
            ]);
        }
        const host = await getField(
            {namespace, resource: `service/${name}`, jsonPath: '{.spec.externalName}'},
            io,
        );
        const wanted = `${name}.${servicesNamespace}.svc.cluster.local`;
        if (host !== wanted) fail(`${name} resolves to '${host}' from ${namespace}`);
        const port = await getField(
            {namespace, resource: `service/${name}`, jsonPath: '{.spec.ports[0].port}'},
            io,
        );
        // A pod reads only the Secrets of its own namespace, so the values the workload reads are
        // written in the suite's as well — that is the copy the deployment dials the alias with
        // (D-462). Compared rather than counted: two Secrets of one name holding different passwords
        // is the failure this catches, and it is invisible to a check that only asks whether one exists.
        if (await objectExists({namespace: servicesNamespace, resource: `secret/${name}-credentials`}, io)) {
            const beside = await secretData({namespace: servicesNamespace, name: `${name}-credentials`}, io);
            const inSuite = await secretData({namespace, name: `${name}-credentials`}, io);
            if (beside !== inSuite) {
                fail(`${name}-credentials holds different values in ${namespace}`);
            }
            io.log(`${name}-credentials is readable in ${namespace} with the workload's own values`);
        }
        await dialFromSuite({namespace, name, port}, io);
    }
    await io.run('kubectl', ['-n', servicesNamespace, 'get', 'deployment,service,pvc']);
};

/** One Secret's values, in a form two copies can be compared in. */
const secretData = async (
    {namespace, name}: {namespace: string; name: string},
    io: IStepIo,
): Promise<string> => {
    const secret = await getJson<{data?: Record<string, string>}>(
        {namespace, resource: `secret/${name}`},
        io,
    );
    return JSON.stringify(Object.entries(secret?.data ?? {}).sort());
};

/**
 * Dial the alias from a process of the suite, in the suite's namespace.
 *
 * The name in the realm's config is the only form a deployment ever uses, so resolving it there is the
 * claim. The pod is chosen by *container* readiness rather than by phase (F-441), and `node --version`
 * is asked before the probe because what runs through `kubectl exec` is an executable, not a shell: a
 * builtin would answer "exec: command: not found" and the probe would be skipped on a process that
 * carries node.
 */
const dialFromSuite = async (
    {namespace, name, port}: {namespace: string; name: string; port: string},
    io: IStepIo,
): Promise<void> => {
    const pod = await readyPodName({namespace}, io);
    if (!pod || !(await podHasNode({namespace, pod}, io))) {
        io.warn('no running pod carrying node — the alias is checked, its resolution is not');
        return;
    }
    const script = [
        'const net = require("net");',
        'const [port, host] = process.argv.slice(1);',
        'const socket = net.connect(Number(port), host);',
        'socket.setTimeout(5000);',
        'socket.on("connect", () => { console.log("connected to " + host); socket.end(); });',
        'socket.on("timeout", () => { console.error("FAIL: timed out dialling " + host); process.exit(1); });',
        'socket.on("error", error => { console.error("FAIL: " + error.message); process.exit(1); });',
    ].join(' ');
    await execInPod({namespace, pod, command: ['node', '-e', script, port, name]}, io);
};

/** The portal objects read back from the cluster, and the round trips a reader would make. */
export const portalChecks = async (
    {namespace, credentials}: {
        namespace: string;
        credentials?: {user?: string; password?: string};
    },
    io: IStepIo,
): Promise<void> => {
    const listed = await io.capture('kubectl', [
        '-n',
        namespace,
        'get',
        'ingress',
        '-o',
        'jsonpath={.items[*].metadata.name}',
    ], {allowFailure: true});
    const ingresses = listed.split(/\s+/).filter(Boolean);
    if (!ingresses.length) {
        io.log('no portal: the suite declares none, or the one it declares has no host');
        return;
    }
    for (const ingress of ingresses) {
        const host = await getField(
            {namespace, resource: `ingress/${ingress}`, jsonPath: '{.spec.rules[0].host}'},
            io,
        );
        const service = await getField(
            {
                namespace,
                resource: `ingress/${ingress}`,
                jsonPath: '{.spec.rules[0].http.paths[0].backend.service.name}',
            },
            io,
        );
        io.log(`${ingress}: host ${host || '<none>'}, backend ${service}`);
        const endpoints = await getField(
            {
                namespace,
                resource: `endpoints/${service}`,
                jsonPath: '{.subsets[*].addresses[*].ip}',
                // A Service with no endpoints still answers for the object itself, which is what the
                // check is about — and a Service that is not there at all is a missing backend rather
                // than a transport error.
                optional: true,
            },
            io,
        );
        if (!endpoints) fail(`${service} has no endpoints, so the portal's path leads nowhere`);
        const forward = await portForward({namespace, service, localPort: 18080}, io);
        try {
            await portalPage(forward, io);
            if (!credentials?.user || !credentials.password) {
                io.warn('BLONG_TEST_USER/BLONG_TEST_PASSWORD unset, so the login round trip was skipped');
                continue;
            }
            await loginRoundTrip(forward, {user: credentials.user, password: credentials.password}, io);
        } finally {
            forward.stop();
        }
    }
};

/** The page, through the Service: `/s/` is the prefix the suite's browser build uses. */
const portalPage = async (forward: IPortForward, io: IStepIo): Promise<void> => {
    const answer = await request(`http://127.0.0.1:${forward.localPort}/s/`);
    if (pageAnswer(answer)) {
        io.log('the portal serves a page at /s/');
        return;
    }
    io.warn(`${forward.localPort} did not answer /s/ with a page — the artifact may carry no bundle`);
};

/**
 * The login round trip — and the two things it says about a released process.
 *
 * A page is not a working deployment: it is static files, and the artifact carried them whether or not
 * a single table exists. `login.token.create` reads and writes the credential tables, so an answer
 * that carries a token is what says the released process reached a schema (T-266, F-415).
 *
 * The endpoint expects an MLE-encrypted request — a plain POST is answered with a 400 that carries
 * jose's key error and reads like a broken key configuration (T-273) — so the round trip goes through
 * `blong-dev proxy`, which is the transport an MLE client uses and makes the answer readable.
 */
const loginRoundTrip = async (
    forward: IPortForward,
    {user, password}: {user: string; password: string},
    io: IStepIo,
): Promise<void> => {
    const proxyPort = 18099;
    // The flags are space-separated because that is the form the CLI documents; `--target=http://…`
    // is read as nothing at all, and the proxy answers on the default port instead — which shows up as
    // a connection refused to a port this run never mentioned.
    const proxy = spawn(
        'blong-dev',
        [
            'proxy',
            '--port',
            `${proxyPort}`,
            '--target',
            `http://127.0.0.1:${forward.localPort}`,
            '--no-login',
        ],
        {stdio: ['ignore', 'ignore', 'pipe']},
    );
    // Kept rather than discarded: a proxy that dies leaves a run waiting for a port nobody is
    // listening on, and its own complaint is the only thing that says why.
    let complaint = '';
    proxy.stderr?.on('data', chunk => (complaint += chunk));
    const stop = () => proxy.kill('SIGTERM');
    try {
        try {
            await waitFor('the proxy', () => portAnswers(proxyPort), {
                timeoutMs: 20_000,
                intervalMs: 250,
            });
        } catch (error) {
            if (complaint.trim()) {
                fail(
                    `the proxy did not come up: ${complaint.trim().split('\n').slice(-4).join('\n')}`,
                );
            }
            throw error;
        }
        const answer = await request(`http://127.0.0.1:${proxyPort}/rpc/login/token/create`, {
            method: 'POST',
            headers: {'content-type': 'application/json'},
            body: JSON.stringify({params: {username: user, password}}),
        });
        if (tokenAnswer(answer)) {
            io.log('the login answers with a token, so the released process reached its credential tables');
        } else {
            io.warn(`the login did not answer with a token: ${answer}`);
        }
        // The answer carries the pair a client uses to verify the server and to encrypt to it, and it
        // may carry only the public halves: the private signing key behind this deployment mints tokens
        // the gateway verifies, so a `d` here hands the deployment to every caller who can log in
        // (T-274). This is the assertion, and a leak fails the run rather than warning.
        const private_ = privateKeyFields(answer);
        if (private_.length) fail(`the login answer carries private key material: ${private_.join(', ')}`);
        io.log('the login answer carries no private key material');
        // A released process publishes the CRUD validations of its public models, and that is a claim
        // about two modules agreeing: the port collects the models into a store at the package root and
        // `subject.validation` reads it (D-459). When they disagree the process still starts and the
        // gateway still accepts everything — which is how a released suite passed every check while
        // serving payloads no model allows (F-437). Asking for a type violation is what tells the two
        // apart, and the call is an `edit` of an id no suite has, so a run without validations writes
        // nothing.
        const refusal = await request(`http://127.0.0.1:${proxyPort}/rpc/access/access/edit`, {
            method: 'POST',
            headers: {'content-type': 'application/json'},
            body: JSON.stringify({
                params: {
                    access: {
                        accessId: '00000000-0000-0000-0000-000000000000',
                        isActive: 'not-a-boolean',
                    },
                },
            }),
        });
        if (validationRefusal(refusal)) {
            io.log('and the published validation refuses a payload the model does not allow');
        } else {
            io.warn(`the gateway answered no validation refusal: ${refusal}`);
        }
    } finally {
        stop();
    }
};

/** One request, with its failure as an empty answer: an unreachable portal is a warning, not a crash. */
const request = async (url: string, init?: RequestInit): Promise<string> => {
    try {
        const response = await fetch(url, {...init, signal: AbortSignal.timeout(20_000)});
        return await response.text();
    } catch {
        return '';
    }
};

/** Where the suite's version directory has to be on each node, which no object can show. */
export const suiteVersionDirectoryReport = async (
    {namespace}: {namespace: string},
    io: IStepIo,
): Promise<void> => {
    const listed = await io.capture('kubectl', ['get', 'nodes', '-o', 'name'], {allowFailure: true});
    for (const node of listed
        .split('\n')
        .map(line => line.replace(/^node\//, '').trim())
        .filter(Boolean)) {
        const known = await io.capture('k3d', ['node', 'get', node], {allowFailure: true});
        io.log(
            known.length
                ? `${node}: check /var/lib/blong/suites/${namespace}/ inside the node`
                : `${node}: unknown`,
        );
    }
};
