/**
 * scripts/lib/trees.ts — the two trees a run generates before it applies anything.
 *
 * Both are written by the same framework CLI, on the `k8s` intent, and they are generated rather than
 * applied from the repository on purpose: the committed trees name the published framework image, and
 * a run that brought its own image has to say so. The operator's tree is written from *this* realm
 * (its own entry), the suite's from whatever entry the caller names — which is what makes one file
 * serve a CI job, a developer's cycle and a suite that is not `blong-suite` at all.
 */
import {resolve} from 'node:path';

import {namespaceFileNames} from './artifacts.ts';
import type {IStepIo} from './exec.ts';
import {serviceOffArguments, servicesNamespaceFromNames} from './rules.ts';

/** The framework's own entry, which a tree is generated by. */
export const frameworkEntry = (root: string): string => `${root}/core/blong-gogo/bin/blong.ts`;

/**
 * The suite's tree, generated where the caller says — `system/kustomize` under the suite's package.
 *
 * The entry is resolved against the caller's working directory and the process is left in it: the
 * framework reads its configuration relative to where it was started, so a runbook that wandered out
 * of the suite's folder to find the entry would generate a tree for the wrong suite.
 */
export const suiteTreeGenerate = async (
    {
        root,
        entry,
        tree,
        serviceOff,
        digest,
    }: {
        root: string;
        /** The suite's entry, relative to the caller's working directory. */
        entry: string;
        tree: string;
        /** A service the deployment runs itself: `mysql`. */
        serviceOff?: string;
        /** The digest of the artifact being deployed, which names the volume it lands in (D-469). */
        digest?: string;
    },
    io: IStepIo,
): Promise<void> => {
    await io.run('rm', ['-rf', tree]);
    if (serviceOff) io.log(`the deployment runs ${serviceOff} itself`);
    const digestArgs = digest ? [`--kustomize.deploy.suiteVolume.artifact.digest=${digest}`] : [];
    await io.run('node', [
        '--conditions=development',
        frameworkEntry(root),
        resolve(entry),
        'k8s',
        // Split, because this tree is the one the *repository* keeps: a base that holds nothing this
        // deploy owns, and a gitignored overlay beside it that holds the rest (D-475).
        '--kustomize.deploy.layout=split',
        ...serviceOffArguments(serviceOff),
        ...digestArgs,
    ]);
};

/**
 * The operator's install tree: the Deployment, the cluster-scoped rights and the CRD.
 *
 * One operator per cluster (Phase 15 A), and a suite tree deliberately carries none of this. The
 * result is the tenant tree, not the operator tree.
 *
 * `artifactUrl` overrides where the operator's own artifact comes from, because the operator runs this
 * realm and fetches what it runs the way every process does. It is passed as
 * `suiteVolume.artifact.url` — a sibling of `suite` in the plan's config rather than a member of it —
 * because the cache DaemonSet the install tree writes fetches whatever that names, and a nested
 * spelling is dropped without a word (F-396, F-404).
 */
export const operatorTreeGenerate = async (
    {
        root,
        outputDir,
        frameworkImage,
        version,
        artifactUrl,
        digest,
    }: {
        root: string;
        outputDir: string;
        frameworkImage: string;
        version: string;
        artifactUrl?: string;
        /** The digest of the operator's own artifact, from the same publisher (D-469). */
        digest?: string;
    },
    io: IStepIo,
): Promise<void> => {
    await io.run('rm', ['-rf', outputDir]);
    const args = [
        '--conditions=development',
        frameworkEntry(root),
        `${root}/realm/blong-kustomize/operator-entry.ts`,
        'k8s',
        `--kustomize.deploy.outputDir=${outputDir}`,
        `--kustomize.deploy.suite.frameworkImage=${frameworkImage}`,
        `--kustomize.deploy.suite.minFrameworkVersion=${version}`,
        // Split, like the suite's tree: the operator's install is a repository tree too, and its base is
        // what a reader compares between revisions (D-475).
        '--kustomize.deploy.layout=split',
    ];
    if (artifactUrl) args.push(`--kustomize.deploy.suiteVolume.artifact.url=${artifactUrl}`);
    if (digest) args.push(`--kustomize.deploy.suiteVolume.artifact.digest=${digest}`);
    // From the realm's own folder: this is the realm that is being generated, and its configuration is
    // read relative to it.
    await io.run('node', args, {cwd: `${root}/realm/blong-kustomize`});
};

/** Where the generated service workloads went, read off the tree rather than declared. */
export const servicesNamespaceOf = ({
    tree,
    suiteNamespace,
}: {
    tree: string;
    suiteNamespace: string;
}): string | undefined => servicesNamespaceFromNames(namespaceFileNames(tree), suiteNamespace);
