#!/bin/sh
#
# This Git hook is called by "git commit" with no arguments.
# It lints staged files before the commit is recorded.
#
# This hook was installed by Rush. To learn more about Rush, visit: https://rushjs.io
# To learn more about Git hooks, visit: https://git-scm.com/docs/githooks
#
# TODO: Activate by removing the "exit 0" line below once blong-dev is wired up:
#
#   1. Add @feasibleone/blong-dev as a devDependency to each package that needs linting
#   2. Set "ci-lint": "blong-dev lint" in each package's scripts
#
# How it works: blong-dev lint-staged reads staged files from git, maps them to their
# owning Rush package (via rush.json projectFolder), and runs `blong-dev lint <files>`
# in each affected package directory.  Each package's node_modules/.bin is used to
# resolve tsc / cspell / eslint so no global installs are required.
#
# See: https://heft.rushstack.io/pages/intro/rig_packages/ for future rig alignment.

exit 0  # remove this line to activate

node core/blong-dev/bin/blong-dev.ts lint-staged || exit $?
