apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: blong-kustomize
    app.kubernetes.io/name: blong-suite
    app.kubernetes.io/part-of: blong-suite
    app.kubernetes.io/version: 1.13.0
    blong.feasible.one/spec-hash: 00f14e7b9ee5a915
  name: db
  namespace: blong-suite
spec:
  externalName: mysql.blong-integration.svc.cluster.local
  ports:
    - name: mysql
      port: 3306
  type: ExternalName
