import {spawnSync} from 'node:child_process';
import {existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync} from 'node:fs';
import {readdir} from 'node:fs/promises';
import {basename, dirname, join, relative, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import t from 'tap';

import type {PrimitiveHost} from './engine.ts';
import {ADDED_OBJECT, FIXTURE, SUBJECT, regenerateFixture} from './fixture.ts';
/**
 * The end-to-end proof that kukum's output is not merely syntactically valid.
 *
 * The realm in `test/fixture/e2e-realm/` is **generated by this suite on every
 * run** — the generated files are gitignored. Only its Playwright baselines are
 * committed, and they are what pins the generated UI: a template change that
 * alters the rendered page fails here until the baselines are deliberately
 * refreshed with `node --run kukum:fixture:update`.
 *
 * On top of the template realm the suite adds a second entity (`gadget`) through
 * the API — the realm's own `widget` stays the working baseline — and then runs
 * the realm's **three** test legs:
 *
 *   - server tap: adds a `gadget` and finds it again
 *   - browser tap: the same over HTTP through the gateway, so RBAC is exercised
 *   - Playwright: the generated model page, against the committed baselines
 *
 * Finally it asserts an artifact → test matrix: every primitive the API added is
 * referenced by at least one of those tests. Without that the suite would pass
 * even if a generated test body were empty, or if a group were written but never
 * registered — a group missing from `integration.watch.test` silently never runs.
 *
 * Requires the local dev database, and browsers for the Playwright leg.
 * Skip with `KUKUM_SKIP_E2E=1`, or just the browser leg with
 * `KUKUM_SKIP_PLAYWRIGHT=1`.
 */

const host: PrimitiveHost = {
    existsSync,
    readFileSync,
    writeFileSync,
    mkdirSync: path => mkdirSync(path, {recursive: true}),
    scan: async (...path: string[]) => readdir(join(...path), {withFileTypes: true}),
    statSync,
    join,
    dirname,
    basename,
    relative,
    resolve,
};

const HERE = fileURLToPath(new URL('.', import.meta.url));
const ADDED_NAME = 'Gadget';
const blongDevBin = fileURLToPath(new URL('./node_modules/.bin/blong-dev', import.meta.url));
const PATH_SEP = process.platform === 'win32' ? ';' : ':';
const SNAPSHOTS = join(FIXTURE, `test/${SUBJECT}.play.ts-snapshots`);

/**
 * Bins the fixture cannot provide for itself.
 *
 * The fixture is not a Rush project, so it has no `node_modules` of its own:
 * `blong` / `blong-watch` / `playwright` come from blong-kukum's tree and Vite —
 * which the Playwright config needs to serve the browser side — from
 * blong-browser's. Both are only ever put on PATH for these runs.
 */
const TOOL_BINS = [
    join(HERE, 'node_modules', '.bin'),
    fileURLToPath(new URL('../blong-browser/node_modules/.bin', import.meta.url)),
];

/** The primitives this suite adds on top of the scaffolded realm. */
const skipped = process.env.KUKUM_SKIP_E2E === '1';
const skipPlaywright = skipped || process.env.KUKUM_SKIP_PLAYWRIGHT === '1';

// The Playwright leg starts a dev server, a Vite server and a browser; tap's
// default per-file budget is far too short for that.
t.setTimeout(900_000);

const read = (path: string): string => readFileSync(join(FIXTURE, path), 'utf8');
const has = (path: string): boolean => existsSync(join(FIXTURE, path));

function runFixture(
    args: string[],
    env: Record<string, string> = {},
): {output: string; status: number | null} {
    const run = spawnSync(blongDevBin, args, {
        cwd: FIXTURE,
        encoding: 'utf8',
        timeout: 900_000,
        env: {
            ...process.env,
            ...env,
            PATH: [...TOOL_BINS, process.env['PATH'] ?? ''].join(PATH_SEP),
        },
    });
    return {output: `${run.stdout ?? ''}${run.stderr ?? ''}`, status: run.status};
}

/** A missing database or browser is an environment gap, not a scaffolding failure. */
const DB_MISSING = /ECONNREFUSED|ER_ACCESS_DENIED|getaddrinfo|connect ECONN|Cannot connect/i;
const NO_BROWSER = /Executable doesn't exist|browserType\.launch/i;

t.test('the fixtures are regenerated from the templates on every run', {skip: skipped}, async t => {
    const results = await regenerateFixture(host);

    t.ok(
        results.every(result => result.files.length),
        'every primitive produced files',
    );
    for (const expected of [
        `meta/type/${ADDED_OBJECT}.ts`,
        `server/test/test/test${ADDED_NAME}.ts`,
        `browser/test/test/test${ADDED_NAME}.flow.ts`,
        `meta/model/${SUBJECT}${ADDED_NAME}Model.ts`,
    ]) {
        t.ok(has(expected), `regenerated ${expected}`);
    }

    // A generated group nobody lists never executes, so a notice here is a
    // failure rather than a cosmetic message.
    t.same(
        results
            .flatMap(result => result.messages ?? [])
            .filter(message => /could not/.test(message)),
        [],
        'every generated test group was registered',
    );

    // The baselines are the one part of the fixture the generators do not
    // produce, and the only part under version control.
    t.ok(
        existsSync(SNAPSHOTS) && readdirSync(SNAPSHOTS).length > 0,
        'the committed baselines survived the regeneration',
    );
});

t.test(
    'the realm runs its server and browser tests over the added entity',
    {skip: skipped},
    async t => {
        const {output, status} = runFixture(['test']);

        if (DB_MISSING.test(output)) {
            t.pass('skipped: the local dev database is not reachable');
            return;
        }

        t.equal(status, 0, 'the realm suite exits 0');
        t.notOk(/^not ok/m.test(output), 'no tap failures');

        // The added entity must be *executed*, not merely present in the tree.
        t.match(output, /\bok \d+ - addGadget\b/, 'the added server test ran: add');
        t.match(output, /\bok \d+ - findGadget\b/, 'the added server test ran: find');
        t.match(output, /\bok \d+ - e2e flow browser\b/, 'the added browser group ran');
    },
);

t.test('every added primitive is covered by those tests', {skip: skipped}, t => {
    const matrix: Array<[string, boolean]> = [
        [
            'meta/type/gadget.ts declares the table',
            /gadget: type\.Object/.test(read(`meta/type/${ADDED_OBJECT}.ts`)),
        ],
        [
            'meta/db/db.ts registers the table',
            read('meta/db/db.ts').includes(`'${SUBJECT}.${ADDED_OBJECT}'`),
        ],
        [
            'meta/dbTest seeds the table',
            has(`meta/dbTest/${SUBJECT}${ADDED_NAME}Merge.yaml`) &&
                read(`meta/dbTest/${SUBJECT}${ADDED_NAME}Merge.yaml`).includes(ADDED_OBJECT),
        ],
        [
            'the RBAC seed grants it, or every gateway call would be denied',
            read('meta/dbTest/accessAuthorizationMerge.yaml').includes(
                `${SUBJECT}${ADDED_NAME}Add`,
            ),
        ],
        [
            'meta/model describes the entity',
            new RegExp(`${ADDED_OBJECT}\\.${ADDED_OBJECT}Name`).test(
                read(`meta/model/${SUBJECT}${ADDED_NAME}Model.ts`),
            ),
        ],
        [
            'the server group drives the generated handler',
            /e2eGadgetAdd/.test(read('server/test/test/testGadget.ts')) &&
                /e2eGadgetFind/.test(read('server/test/test/testGadget.ts')),
        ],
        [
            'the browser group drives it over HTTP',
            /e2eGadgetAdd/.test(read('browser/test/test/testGadget.flow.ts')),
        ],
        [
            'index.ts lists the server group, so it actually runs',
            read('index.ts').includes(`'test.${ADDED_OBJECT}'`),
        ],
        [
            'browser-test.ts lists the browser group, so it actually runs',
            read('browser-test.ts').includes(`'test.${ADDED_OBJECT}.flow'`),
        ],
        [
            'the Playwright spec describes the entity',
            new RegExp(`test\\.describe\\('${ADDED_NAME}'`).test(read(`test/${SUBJECT}.play.ts`)),
        ],
    ];

    const uncovered = matrix.filter(([, covered]) => !covered).map(([name]) => name);
    t.same(uncovered, [], `all ${matrix.length} artifacts are covered`);
    t.end();
});

t.test(
    'the Playwright leg drives the model page against committed baselines',
    {skip: skipPlaywright},
    async t => {
        const baselines = existsSync(SNAPSHOTS) ? readdirSync(SNAPSHOTS) : [];
        t.ok(
            baselines.some(name => name.startsWith('e2e-gadget-browse')),
            'the added entity has committed baselines',
        );

        const {output, status} = runFixture(['playwright'], {
            // The fixture cannot derive ports from `rush.json`, so both are pinned.
            PLAYWRIGHT_BACKEND_PORT: '8191',
            PLAYWRIGHT_FRONTEND_PORT: '5291',
        });

        if (DB_MISSING.test(output)) {
            t.pass('skipped: the local dev database is not reachable');
            return;
        }
        if (NO_BROWSER.test(output)) {
            t.pass('skipped: Playwright browsers are not installed');
            return;
        }

        t.equal(status, 0, 'the Playwright suite exits 0');
        t.match(output, new RegExp(`${ADDED_NAME} › browse`), 'the added entity was browsed');
    },
);
