import {existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync} from 'node:fs';
import {readdir} from 'node:fs/promises';
import {basename, dirname, join, relative, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import t from 'tap';

import {PREDICATES, type Predicate, type PrimitiveHost} from './engine.ts';
import {type OperationParams, type OperationResult} from './operation.ts';
import addOperation from './orchestrator/kukum/add.ts';
import {PRIMITIVES} from './primitives/index.ts';

/**
 * End-to-end check of the scaffolding API.
 *
 * 1. Scaffolds a complete realm through the API (`realm add` delegates to the
 *    `blong-kopi` template, so the result is a runnable package).
 * 2. Runs that realm's own suite and asserts the expected test entry points are
 *    present and green.
 * 3. Adds every primitive, in every kind, into the same realm.
 *
 * Step 3 runs last on purpose: several generators are whole-file by design
 * (`schema` rewrites `meta/type/schema.ts`, `model` writes a single spec), so
 * adding them over a scaffolded realm replaces template artifacts rather than
 * merging into them. Runability is a property of the scaffold, and is asserted
 * before those replacements happen.
 *
 * The realm is nested inside this package so Node resolves the framework
 * packages from the ancestor `node_modules` without an install.
 *
 * Slow and dependent on the local dev database, so it is opt-out via
 * `KUKUM_SKIP_E2E=1` and keeps its artifacts with `KUKUM_KEEP=1`.
 */

/**
 * Call an operation the way the runtime does: build the `library()` factory,
 * then call the result with the `this` the framework seeds.
 *
 * Every step here is `add`, so that is the only predicate wired in.
 */
const build = <T>(mod: unknown): T => (mod as (api: object) => T)({config: {}});

const operate = (
    platform: PrimitiveHost,
    id: string,
    predicate: Predicate,
    params: OperationParams,
): Promise<OperationResult> => {
    if (predicate !== 'add') throw new Error(`operation '${predicate}' is not wired in here`);
    return build<(this: object, id: string, params: OperationParams) => Promise<OperationResult>>(
        addOperation,
    ).call({platform}, id, params);
};

const host: PrimitiveHost = {
    existsSync,
    readFileSync,
    writeFileSync,
    mkdirSync: path => mkdirSync(path, {recursive: true}),
    scan: async (...path: string[]) => readdir(join(...path), {withFileTypes: true}),
    statSync,
    join,
    dirname,
    basename,
    relative,
    resolve,
};

const HERE = fileURLToPath(new URL('.', import.meta.url));
const REALM_ROOT = join(HERE, '.kukum-test', 'e2e');
/**
 * Single-word on purpose: the realm template substitutes `$subject` into
 * identifiers and derives seed method names from `<subject><Object>Merge`, so
 * multi-word names produce a realm whose seeds cannot dispatch.
 */
const SUBJECT = 'e2e';
const OBJECT = 'widget';

t.before(() => {
    rmSync(REALM_ROOT, {recursive: true, force: true});
    mkdirSync(REALM_ROOT, {recursive: true});
});
t.teardown(() => {
    // Only this suite's own directory: `.kukum-test` is shared with
    // `e2e.test.ts`, which tap runs in parallel, and removing the whole folder
    // would pull the scratch realm out from under it mid-run.
    if (!process.env.KUKUM_KEEP) rmSync(REALM_ROOT, {recursive: true, force: true});
});

const skipped = process.env.KUKUM_SKIP_E2E === '1';

t.test('scaffolds a full realm through the API', {skip: skipped}, async t => {
    const result = await operate(host, 'realm', 'add', {
        target: REALM_ROOT,
        subject: SUBJECT,
        object: OBJECT,
        instructions: ['generated by the kukum end-to-end test'],
    });

    t.ok(result.written.length >= 20, `realm tree written (${result.written.length} files)`);
    for (const expected of [
        'package.json',
        'server.ts',
        'browser.ts',
        'index.ts',
        'index.test.ts',
        'browser-test.ts',
        'tsconfig.json',
        'playwright.config.ts',
        'meta/type/schema.ts',
        'meta/db/db.ts',
        'orchestrator/subject/init.ts',
        `meta/model/${SUBJECT}${OBJECT[0].toUpperCase()}${OBJECT.slice(1)}Model.ts`,
    ]) {
        t.ok(existsSync(join(REALM_ROOT, expected)), `template file ${expected} exists`);
    }

    // The template's own test entry points must survive the scaffold.
    // (`$Object` is the entity name, so they are `test<Object>.ts`.)
    const Object = OBJECT[0].toUpperCase() + OBJECT.slice(1);
    for (const testEntry of [
        `server/test/test/test${Object}.ts`,
        `browser/test/test/test${Object}.flow.ts`,
        `test/${SUBJECT}.play.ts`,
    ]) {
        t.ok(existsSync(join(REALM_ROOT, testEntry)), `template test ${testEntry} exists`);
    }

    const pkg = JSON.parse(readFileSync(join(REALM_ROOT, 'package.json'), 'utf8')) as {
        name: string;
    };
    t.equal(pkg.name, SUBJECT, 'package name substituted');
});

t.test('adds every primitive and kind into the scaffolded realm', {skip: skipped}, async t => {
    const failures: string[] = [];
    let writes = 0;
    let kinds = 0;

    for (const primitive of PRIMITIVES) {
        for (const kind of primitive.kinds) {
            kinds += 1;
            try {
                const result = await operate(host, primitive.id, 'add', {
                    target: REALM_ROOT,
                    subject: SUBJECT,
                    object: OBJECT,
                    kind,
                    // A custom (non-well-known) layer needs an explicit folder name.
                    layer: kind === 'custom' ? 'e2eExtra' : undefined,
                    params: {predicate: 'check'},
                    instructions: [`${primitive.id}/${kind} from the e2e test`],
                });
                writes += result.written.length;
                if (!result.files.length)
                    failures.push(`${primitive.id}/${kind}: no files planned`);
                for (const file of result.files) {
                    if (!existsSync(join(REALM_ROOT, file.path)))
                        failures.push(`${primitive.id}/${kind}: ${file.path} missing on disk`);
                }
            } catch (error) {
                failures.push(`${primitive.id}/${kind}: ${(error as Error).message}`);
            }
        }
    }

    t.same(failures, [], 'every primitive kind scaffolded without error');
    t.ok(kinds >= 25, `covered ${kinds} primitive kinds`);
    t.ok(writes > 0, `wrote ${writes} file(s)`);

    // The test kinds must contribute their own entry points.
    const added = [
        `server/test/test/test${OBJECT[0].toUpperCase()}${OBJECT.slice(1)}.ts`,
        `browser/test/test/test${OBJECT[0].toUpperCase()}${OBJECT.slice(1)}.flow.ts`,
    ];
    for (const entry of added) {
        t.ok(existsSync(join(REALM_ROOT, entry)), `added test entry ${entry} present`);
    }
});

// Keep the predicate list referenced so the test fails loudly if the API drops one.
t.test('generated artifacts carry their agent instructions', {skip: skipped}, t => {
    const handler = `orchestrator/${SUBJECT}/${SUBJECT}${OBJECT[0].toUpperCase()}${OBJECT.slice(1)}Check.ts`;
    t.ok(existsSync(join(REALM_ROOT, handler)), `${handler} was generated`);
    if (existsSync(join(REALM_ROOT, handler))) {
        const source = readFileSync(join(REALM_ROOT, handler), 'utf8');
        t.ok(/@kukum-instructions:/.test(source), 'instructions embedded in generated source');
        t.ok(/import unchanged from/.test(source), 'generated marker preserved');
    }
    t.end();
});

t.test('every primitive advertises the standard predicates', {skip: skipped}, t => {
    for (const primitive of PRIMITIVES) {
        t.same(
            [...PREDICATES],
            ['find', 'get', 'add', 'edit', 'check'],
            `${primitive.id} predicates unchanged`,
        );
    }
    t.end();
});
