import {handler, type IAssert} from '@feasibleone/blong';

type PersonRow = {
    personId?: string;
    personName?: string;
    personEmail?: string;
    personDescription?: string | null;
    granted?: boolean;
};
type TeamRow = {
    teamId?: string;
    teamName?: string;
    teamDescription?: string | null;
};
type StepMeta = {$meta: Record<string, unknown>};

/**
 * testMysqlResource — integration coverage for the resource-backed + graph-edge
 * knex adapter features (declarative `ISchemaTable.resource` / `edges`):
 *
 *   - `add` generates the server-side PK + `core_resource` row for a
 *     resource-backed `uidNotNull` PK and joins `${object}Name` onto the result;
 *   - `get` / `find` join the display name from `core_resource.resourceName`;
 *   - `edit` renames `core_resource.resourceName` from `${object}Name`;
 *   - `remove` cascades the `core_resource` row (after the entity row);
 *   - graph-edge master-detail: `get` attaches the `hasMember` rows, `add` /
 *     `edit` diff-sync the `core_triple` edges (filtering `granted !== false`),
 *     `remove` cleans them;
 *   - `type.ulid()` / `type.uuid()` PKs are generated by the generic `add`;
 *   - requests accept real ULID/UUID strings (26-char Crockford / 36-char
 *     dashed UUID) on add/get/find for binary(16) PK columns.
 *
 * Steps run in a sequential dependency chain. Setup wipes the test tables.
 */
export default handler(
    ({
        lib: {group},
        handler: {
            sqlResourceSetup,
            sqlPersonAdd,
            sqlPersonGet,
            sqlPersonFind,
            sqlPersonEdit,
            sqlPersonRemove,
            sqlTeamAdd,
            sqlTeamGet,
            sqlTeamEdit,
            sqlTeamRemove,
            sqlUlidAdd,
            sqlUlidGet,
            sqlUlidFind,
            sqlUuidAdd,
            sqlUuidGet,
        },
    }) => ({
        testMysqlResource: ({name = 'mysql resource/edge CRUD'}: {name?: string} = {}) =>
            group(name, {
                mask: ['personId', 'teamId', 'itemId', '*.personId', '*.teamId', '*.itemId'],
            })([
                // ── 0. Cleanup ─────────────────────────────────────────────
                async function setup(assert: IAssert, {$meta}: StepMeta) {
                    const result = await sqlResourceSetup<{cleaned: boolean}>({}, $meta);
                    assert.ok(result?.cleaned, 'resource test tables cleaned');
                    return {ready: true};
                },

                // ── 1. resource add — generates PK + resource row ──────────
                async function addPerson(
                    assert: IAssert,
                    {$meta, setup}: StepMeta & {setup: Promise<unknown>},
                ) {
                    await setup;
                    const result = await sqlPersonAdd<{person: PersonRow & {personId: string}}>(
                        {
                            person: {
                                personName: 'Alice',
                                personEmail: 'alice@example.com',
                                personDescription: 'integration person',
                            },
                        },
                        $meta,
                    );
                    assert.ok(result.person?.personId, 'add generated a personId');
                    assert.notEqual(result.person.personId, '', 'generated personId is not empty');
                    assert.equal(result.person.personName, 'Alice', 'add result joins personName');
                    assert.equal(
                        result.person.personEmail,
                        'alice@example.com',
                        'add returns the email column',
                    );
                    return result.person;
                },

                // ── 2. resource get — name joined from core_resource ───────
                async function getPerson(
                    assert: IAssert,
                    {
                        $meta,
                        addPerson,
                    }: StepMeta & {addPerson: Promise<PersonRow & {personId: string}>},
                ) {
                    const created = await addPerson;
                    const result = await sqlPersonGet<{person: PersonRow}>(
                        {personId: created.personId},
                        $meta,
                    );
                    assert.equal(result.person.personName, 'Alice', 'get joins personName');
                    assert.equal(
                        result.person.personEmail,
                        'alice@example.com',
                        'get returns the email column',
                    );
                    return created;
                },

                // ── 3. resource find — name joined on each row ─────────────
                async function findPerson(
                    assert: IAssert,
                    {
                        $meta,
                        getPerson,
                    }: StepMeta & {getPerson: Promise<PersonRow & {personId: string}>},
                ) {
                    const created = await getPerson;
                    const result = await sqlPersonFind<PersonRow[]>(
                        {personEmail: 'alice@example.com'},
                        $meta,
                    );
                    assert.ok(Array.isArray(result) && result.length >= 1, 'find returns rows');
                    assert.equal(result[0].personName, 'Alice', 'find joins personName');
                    return created;
                },

                // ── 4. resource edit — renames core_resource.resourceName ──
                async function editPerson(
                    assert: IAssert,
                    {
                        $meta,
                        findPerson,
                    }: StepMeta & {findPerson: Promise<PersonRow & {personId: string}>},
                ) {
                    const created = await findPerson;
                    await sqlPersonEdit(
                        {
                            person: {
                                personId: created.personId,
                                personName: 'Alice Renamed',
                                personEmail: 'alice@example.com',
                                personDescription: 'edited',
                            },
                        },
                        $meta,
                    );
                    const after = await sqlPersonGet<{person: PersonRow}>(
                        {personId: created.personId},
                        $meta,
                    );
                    assert.equal(
                        after.person.personName,
                        'Alice Renamed',
                        'edit renames the resource',
                    );
                    return created;
                },

                // ── 5. ulid PK — generated by the generic add ──────────────
                async function addUlid(
                    assert: IAssert,
                    {$meta, editPerson}: StepMeta & {editPerson: Promise<unknown>},
                ) {
                    await editPerson;
                    const result = await sqlUlidAdd<{ulid: {ulidId: string; itemName: string}}>(
                        {ulid: {ulidId: 'ulid', itemName: 'ULID-1'}},
                        $meta,
                    );
                    assert.ok(result.ulid?.ulidId, 'ulid add generated an ulidId');
                    // All binary(16) columns round-trip as 24-char base64; the
                    // important part is the placeholder was replaced by a real id.
                    assert.equal(result.ulid.ulidId.length, 24, 'ulid PK is a 16-byte base64 id');
                    assert.notEqual(result.ulid.ulidId, 'ulid', 'ulid placeholder replaced');
                    assert.equal(result.ulid.itemName, 'ULID-1', 'ulid add returns columns');
                    return {ulidId: result.ulid.ulidId};
                },

                // ── 6. uuid PK — generated by the generic add ──────────────
                async function addUuid(
                    assert: IAssert,
                    {$meta, addUlid}: StepMeta & {addUlid: Promise<unknown>},
                ) {
                    await addUlid;
                    const result = await sqlUuidAdd<{uuid: {uuidId: string; itemName: string}}>(
                        {uuid: {uuidId: 'uuid', itemName: 'UUID-1'}},
                        $meta,
                    );
                    assert.ok(result.uuid?.uuidId, 'uuid add generated an uuidId');
                    assert.notEqual(result.uuid.uuidId, 'uuid', 'uuid placeholder replaced');
                    assert.equal(result.uuid.itemName, 'UUID-1', 'uuid add returns columns');
                    return {uuidId: result.uuid.uuidId};
                },

                // ── 7. request accepts a real 26-char Crockford ULID ───────
                async function ulidReal(
                    assert: IAssert,
                    {$meta, addUuid}: StepMeta & {addUuid: Promise<unknown>},
                ) {
                    await addUuid;
                    // cspell:disable-next-line
                    const realUlid = '01ARZ3NDEKTSV4RRFFQ69G5FAV';
                    // Explicit real-format PK on add (not the placeholder marker).
                    const created = await sqlUlidAdd<{ulid: {ulidId: string; itemName: string}}>(
                        {ulid: {ulidId: realUlid, itemName: 'ULID-REAL'}},
                        $meta,
                    );
                    assert.equal(
                        created.ulid.ulidId.length,
                        24,
                        'explicit ulid PK returns as base64',
                    );
                    // get by the real ULID string
                    const got = await sqlUlidGet<{ulid: {ulidId: string; itemName: string}}>(
                        {ulidId: realUlid},
                        $meta,
                    );
                    assert.ok(got.ulid, 'get finds the row by a real ULID string');
                    assert.equal(got.ulid.itemName, 'ULID-REAL', 'get returns the explicit row');
                    // find by the real ULID string
                    const found = await sqlUlidFind<{ulidId: string; itemName: string}[]>(
                        {itemName: 'ULID-REAL'},
                        $meta,
                    );
                    assert.ok(found.length >= 1, 'find returns the explicit-ulid row');
                    return {realUlid};
                },

                // ── 8. request accepts a real 36-char dashed UUID ──────────
                async function uuidReal(
                    assert: IAssert,
                    {$meta, ulidReal}: StepMeta & {ulidReal: Promise<unknown>},
                ) {
                    await ulidReal;
                    const realUuid = '123e4567-e89b-12d3-a456-426614174000';
                    const created = await sqlUuidAdd<{uuid: {uuidId: string; itemName: string}}>(
                        {uuid: {uuidId: realUuid, itemName: 'UUID-REAL'}},
                        $meta,
                    );
                    assert.equal(
                        created.uuid.uuidId.length,
                        24,
                        'explicit uuid PK returns as base64',
                    );
                    const got = await sqlUuidGet<{uuid: {uuidId: string; itemName: string}}>(
                        {uuidId: realUuid},
                        $meta,
                    );
                    assert.ok(got.uuid, 'get finds the row by a real UUID string');
                    assert.equal(got.uuid.itemName, 'UUID-REAL', 'get returns the explicit row');
                    return {realUuid};
                },

                // ── 9. resource add with a hasMember graph edge ────────────
                async function addTeam(
                    assert: IAssert,
                    {
                        $meta,
                        uuidReal,
                        editPerson,
                    }: StepMeta & {
                        uuidReal: Promise<unknown>;
                        editPerson: Promise<PersonRow & {personId: string}>;
                    },
                ) {
                    await uuidReal;
                    const person = await editPerson;
                    const result = await sqlTeamAdd<{
                        team: TeamRow & {teamId: string};
                        person: PersonRow[];
                    }>(
                        {
                            team: {
                                teamName: 'Team Alpha',
                                teamDescription: 'integration team',
                            },
                            person: [{personId: person.personId, granted: true}],
                        },
                        $meta,
                    );
                    assert.ok(result.team?.teamId, 'team add generated a teamId');
                    assert.equal(result.team.teamName, 'Team Alpha', 'team add includes teamName');
                    return result.team;
                },

                // ── 10. resource get attaches the hasMember edge rows ──────
                async function getTeam(
                    assert: IAssert,
                    {$meta, addTeam}: StepMeta & {addTeam: Promise<TeamRow & {teamId: string}>},
                ) {
                    const team = await addTeam;
                    const result = await sqlTeamGet<{team: TeamRow; person: PersonRow[]}>(
                        {teamId: team.teamId},
                        $meta,
                    );
                    assert.ok(Array.isArray(result.person), 'get returns a person array');
                    assert.equal(result.person.length, 1, 'get attaches the member');
                    assert.equal(
                        result.person[0].personName,
                        'Alice Renamed',
                        'edge rows join personName',
                    );
                    assert.equal(result.person[0].granted, true, 'edge row carries granted');
                    return team;
                },

                // ── 11. resource edit syncs the edges (removes the member) ─
                async function editTeam(
                    assert: IAssert,
                    {$meta, getTeam}: StepMeta & {getTeam: Promise<TeamRow & {teamId: string}>},
                ) {
                    const team = await getTeam;
                    await sqlTeamEdit(
                        {
                            team: {
                                teamId: team.teamId,
                                teamName: 'Team Alpha Renamed',
                                teamDescription: 'edited',
                            },
                            person: [],
                        },
                        $meta,
                    );
                    const after = await sqlTeamGet<{team: TeamRow; person: PersonRow[]}>(
                        {teamId: team.teamId},
                        $meta,
                    );
                    assert.equal(
                        after.team.teamName,
                        'Team Alpha Renamed',
                        'edit renames the team resource',
                    );
                    assert.equal(after.person.length, 0, 'edit removed the hasMember edge');
                    return team;
                },

                // ── 12. resource remove cleans the edges + resource row ───
                async function removeTeam(
                    assert: IAssert,
                    {$meta, editTeam}: StepMeta & {editTeam: Promise<TeamRow & {teamId: string}>},
                ) {
                    const team = await editTeam;
                    await sqlTeamRemove({teamId: team.teamId}, $meta);
                    const gone = await sqlTeamGet<{team: TeamRow}>({teamId: team.teamId}, $meta);
                    assert.ok(
                        !gone.team || Object.keys(gone.team).length === 0,
                        'team row + resource removed',
                    );
                    return {removed: true};
                },

                // ── 13. resource remove cascades core_resource ─────────────
                async function removePerson(
                    assert: IAssert,
                    {
                        $meta,
                        removeTeam,
                        editPerson,
                    }: StepMeta & {
                        removeTeam: Promise<unknown>;
                        editPerson: Promise<PersonRow & {personId: string}>;
                    },
                ) {
                    await removeTeam;
                    const person = await editPerson;
                    await sqlPersonRemove({personId: person.personId}, $meta);
                    const gone = await sqlPersonGet<{person: PersonRow}>(
                        {personId: person.personId},
                        $meta,
                    );
                    assert.ok(
                        !gone.person || Object.keys(gone.person).length === 0,
                        'person row + resource removed',
                    );
                    return {cleaned: true};
                },
            ]),
    }),
);
