apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: blong-kustomize
    app.kubernetes.io/name: blong-suite
    app.kubernetes.io/part-of: blong-suite
    app.kubernetes.io/version: 1.13.0
    blong.feasible.one/spec-hash: 7d23091c30da3d71
  name: blong-services
