apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/managed-by: blong-kustomize
    app.kubernetes.io/name: blong-operator
    app.kubernetes.io/part-of: blong-operator
    app.kubernetes.io/version: 0.1.0
    blong.feasible.one/spec-hash: 068767f091b6ee35
  name: blong-operator-artifacts
  namespace: blong-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
