/**
 * End Allure reporting session
 */

import {spawn} from 'node:child_process';
import {existsSync} from 'node:fs';
import {writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import type {IAllureConfig, IAllureCategory} from '../types.js';

/** Lines of CLI output kept when `allure generate` fails. */
const MAX_CLI_LINES = 15;

/**
 * End an Allure reporting session
 * 
 * This flushes any pending results and optionally invokes
 * `allure generate` to create the HTML report.
 * 
 * @param config - Allure configuration
 */
export async function allureSessionEnd(config: IAllureConfig): Promise<void> {
    const outputDir = config.outputDir || 'allure-results';

    // Write categories.json if categories are defined
    if (config.categories && config.categories.length > 0) {
        await writeCategoriesFile(outputDir, config.categories);
    }

    console.log(`Allure results written to: ${outputDir}`);

    // Optionally generate HTML report
    if (config.generateOnEnd) {
        await generateReport(outputDir);
    }
}

/**
 * Write categories.json for failure classification
 */
async function writeCategoriesFile(
    outputDir: string,
    categories: IAllureCategory[],
): Promise<void> {
    const filepath = join(outputDir, 'categories.json');
    await writeFile(filepath, JSON.stringify(categories, null, 2), 'utf-8');
}

/**
 * Invoke the `allure generate` CLI to create the HTML report.
 *
 * The CLI is the one this package depends on, not whatever happens to be on the
 * runner's PATH: a report generated by a different Allure than the one that wrote
 * the results is a support question waiting to happen. Its output is captured and
 * summarised rather than inherited, so a CI log keeps one line per report instead
 * of the CLI's progress bar.
 */
async function generateReport(outputDir: string): Promise<void> {
    const cli = resolveAllureCli();
    if (cli === undefined) {
        throw new Error(
            'allure generate: the allure CLI was not found in this package\'s dependencies',
        );
    }
    const reportDir = 'allure-report';
    // Allure 3 takes the directory to *search* rather than the results directory
    // itself: it looks for `**/allure-results` under `--cwd`, which is the package
    // being tested.
    const child = spawn(
        process.execPath,
        [cli, 'generate', '--cwd', process.cwd(), '--output', reportDir],
        {stdio: ['ignore', 'pipe', 'pipe']},
    );
    let output = '';
    child.stdout?.on('data', (chunk: Buffer) => (output += chunk.toString()));
    child.stderr?.on('data', (chunk: Buffer) => (output += chunk.toString()));

    await new Promise<void>((resolve, reject) => {
        child.on('close', code => {
            if (code === 0) {
                console.log(`Allure report generated: ${reportDir}/index.html`);
                resolve();
                return;
            }
            const tail = output.trim().split('\n').slice(-MAX_CLI_LINES).join('\n');
            reject(
                new Error(`allure generate exited with code ${code}${tail ? `:\n${tail}` : ''}`),
            );
        });
        child.on('error', err => reject(new Error(`Failed to invoke allure CLI: ${err.message}`)));
    });
}

/**
 * Locate the Allure CLI this package depends on.
 *
 * `import.meta.url` is the package that declared the dependency, so its own
 * `node_modules` is where pnpm links it; the working directory is checked after
 * that, which is what a suite with a hoisted install sees.
 */
function resolveAllureCli(): string | undefined {
    const here = fileURLToPath(new URL('..', import.meta.url));
    const candidates = [
        join(here, 'node_modules', 'allure', 'cli.js'),
        join(process.cwd(), 'node_modules', 'allure', 'cli.js'),
    ];
    return candidates.find(candidate => existsSync(candidate));
}
