apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/managed-by: blong-kustomize
    app.kubernetes.io/name: blong-suite
    app.kubernetes.io/part-of: blong-suite
    app.kubernetes.io/version: 1.13.0
    blong.feasible.one/spec-hash: ea158517f1129756
  name: blong-suite-test
  namespace: blong-suite
spec:
  rules:
    - host: blong-suite.test
      http:
        paths:
          - backend:
              service:
                name: web-http
                port:
                  number: 8080
            path: /
            pathType: Prefix
