apiVersion: v1
kind: Secret
metadata:
  labels:
    app: mysql
    app.kubernetes.io/managed-by: blong-kustomize
    app.kubernetes.io/name: blong-suite
    app.kubernetes.io/part-of: blong-suite
    app.kubernetes.io/version: 1.13.0
    blong.feasible.one/spec-hash: d840aa8cb5825dd7
  name: mysql-credentials
  namespace: blong-suite
stringData:
  MYSQL_PASSWORD: b3f59521926bbe05475818db0
  MYSQL_USER: b480d83ab69e231ab95952e71
type: Opaque
