apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: blong-kustomize
    app.kubernetes.io/name: blong-operator
    app.kubernetes.io/part-of: blong-operator
    app.kubernetes.io/version: 0.1.0
    blong.feasible.one/spec-hash: 506f2986a6ab58ef
  name: blong-operator
  namespace: blong-system
