apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: blong-kustomize
    app.kubernetes.io/name: blong-operator
    app.kubernetes.io/part-of: blong-operator
    app.kubernetes.io/version: 0.1.0
    blong.feasible.one/spec-hash: 2788fab6017d08ad
  name: blong-operator
  namespace: blong-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: blong-operator
subjects:
  - kind: ServiceAccount
    name: blong-operator
    namespace: blong-system
