/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict';
exports[
    `keycloak.test.ts > TAP > blong int-adapter > keycloak client CRUD > client-read-snapshots 1`
] = `
Object {
  "getClient": Object {
    "access": Object {
      "configure": true,
      "manage": true,
      "view": true,
    },
    "alwaysDisplayInConsole": false,
    "attributes": "<masked>",
    "authenticationFlowBindingOverrides": Object {},
    "bearerOnly": false,
    "clientAuthenticatorType": "client-secret",
    "clientId": "blong-test-crud-client",
    "consentRequired": false,
    "defaultClientScopes": Array [
      "acr",
      "email",
      "profile",
      "roles",
      "web-origins",
    ],
    "directAccessGrantsEnabled": true,
    "enabled": true,
    "frontchannelLogout": false,
    "fullScopeAllowed": true,
    "id": "<masked>",
    "implicitFlowEnabled": false,
    "name": "Blong Test CRUD Client",
    "nodeReRegistrationTimeout": -1,
    "notBefore": 0,
    "optionalClientScopes": Array [
      "address",
      "phone",
      "offline_access",
      "microprofile-jwt",
    ],
    "protocol": "openid-connect",
    "publicClient": false,
    "redirectUris": Array [],
    "secret": "<masked>",
    "serviceAccountsEnabled": false,
    "standardFlowEnabled": false,
    "surrogateAuthRequired": false,
    "webOrigins": Array [],
  },
  "verifyEdit": Object {
    "access": Object {
      "configure": true,
      "manage": true,
      "view": true,
    },
    "alwaysDisplayInConsole": false,
    "attributes": "<masked>",
    "authenticationFlowBindingOverrides": Object {},
    "bearerOnly": false,
    "clientAuthenticatorType": "client-secret",
    "clientId": "blong-test-crud-client",
    "consentRequired": false,
    "defaultClientScopes": Array [
      "acr",
      "email",
      "profile",
      "roles",
      "web-origins",
    ],
    "directAccessGrantsEnabled": true,
    "enabled": true,
    "frontchannelLogout": false,
    "fullScopeAllowed": true,
    "id": "<masked>",
    "implicitFlowEnabled": false,
    "name": "Blong Test CRUD Client Updated",
    "nodeReRegistrationTimeout": -1,
    "notBefore": 0,
    "optionalClientScopes": Array [
      "address",
      "phone",
      "offline_access",
      "microprofile-jwt",
    ],
    "protocol": "openid-connect",
    "publicClient": false,
    "redirectUris": Array [],
    "secret": "<masked>",
    "serviceAccountsEnabled": false,
    "standardFlowEnabled": false,
    "surrogateAuthRequired": false,
    "webOrigins": Array [],
  },
}
`;

exports[
    `keycloak.test.ts > TAP > blong int-adapter > keycloak client CRUD > getClient > getClient 1`
] = `
Object {
  "access": Object {
    "configure": true,
    "manage": true,
    "view": true,
  },
  "alwaysDisplayInConsole": false,
  "attributes": "<masked>",
  "authenticationFlowBindingOverrides": Object {},
  "bearerOnly": false,
  "clientAuthenticatorType": "client-secret",
  "clientId": "blong-test-crud-client",
  "consentRequired": false,
  "defaultClientScopes": Array [
    "acr",
    "email",
    "profile",
    "roles",
    "web-origins",
  ],
  "directAccessGrantsEnabled": true,
  "enabled": true,
  "frontchannelLogout": false,
  "fullScopeAllowed": true,
  "id": "<masked>",
  "implicitFlowEnabled": false,
  "name": "Blong Test CRUD Client",
  "nodeReRegistrationTimeout": -1,
  "notBefore": 0,
  "optionalClientScopes": Array [
    "address",
    "phone",
    "offline_access",
    "microprofile-jwt",
  ],
  "protocol": "openid-connect",
  "publicClient": false,
  "redirectUris": Array [],
  "secret": "<masked>",
  "serviceAccountsEnabled": false,
  "standardFlowEnabled": false,
  "surrogateAuthRequired": false,
  "webOrigins": Array [],
}
`;

exports[
    `keycloak.test.ts > TAP > blong int-adapter > keycloak client CRUD > verifyEdit > verifyEdit 1`
] = `
Object {
  "access": Object {
    "configure": true,
    "manage": true,
    "view": true,
  },
  "alwaysDisplayInConsole": false,
  "attributes": "<masked>",
  "authenticationFlowBindingOverrides": Object {},
  "bearerOnly": false,
  "clientAuthenticatorType": "client-secret",
  "clientId": "blong-test-crud-client",
  "consentRequired": false,
  "defaultClientScopes": Array [
    "acr",
    "email",
    "profile",
    "roles",
    "web-origins",
  ],
  "directAccessGrantsEnabled": true,
  "enabled": true,
  "frontchannelLogout": false,
  "fullScopeAllowed": true,
  "id": "<masked>",
  "implicitFlowEnabled": false,
  "name": "Blong Test CRUD Client Updated",
  "nodeReRegistrationTimeout": -1,
  "notBefore": 0,
  "optionalClientScopes": Array [
    "address",
    "phone",
    "offline_access",
    "microprofile-jwt",
  ],
  "protocol": "openid-connect",
  "publicClient": false,
  "redirectUris": Array [],
  "secret": "<masked>",
  "serviceAccountsEnabled": false,
  "standardFlowEnabled": false,
  "surrogateAuthRequired": false,
  "webOrigins": Array [],
}
`;

exports[
    `keycloak.test.ts > TAP > blong int-adapter > keycloak group CRUD > getGroup > getGroup 1`
] = `
Object {
  "access": Object {
    "manage": true,
    "manageMembers": true,
    "manageMembership": true,
    "view": true,
    "viewMembers": true,
  },
  "attributes": Object {},
  "clientRoles": Object {},
  "id": "<masked>",
  "name": "blong-test-group",
  "path": "/blong-test-group",
  "realmRoles": Array [],
  "subGroupCount": 0,
  "subGroups": Array [],
}
`;

exports[
    `keycloak.test.ts > TAP > blong int-adapter > keycloak group CRUD > group-read-snapshots 1`
] = `
Object {
  "getGroup": Object {
    "access": Object {
      "manage": true,
      "manageMembers": true,
      "manageMembership": true,
      "view": true,
      "viewMembers": true,
    },
    "attributes": Object {},
    "clientRoles": Object {},
    "id": "<masked>",
    "name": "blong-test-group",
    "path": "/blong-test-group",
    "realmRoles": Array [],
    "subGroupCount": 0,
    "subGroups": Array [],
  },
  "verifyEdit": Object {
    "access": Object {
      "manage": true,
      "manageMembers": true,
      "manageMembership": true,
      "view": true,
      "viewMembers": true,
    },
    "attributes": Object {},
    "clientRoles": Object {},
    "id": "<masked>",
    "name": "blong-test-group-updated",
    "path": "/blong-test-group-updated",
    "realmRoles": Array [],
    "subGroupCount": 0,
    "subGroups": Array [],
  },
}
`;

exports[
    `keycloak.test.ts > TAP > blong int-adapter > keycloak group CRUD > verifyEdit > verifyEdit 1`
] = `
Object {
  "access": Object {
    "manage": true,
    "manageMembers": true,
    "manageMembership": true,
    "view": true,
    "viewMembers": true,
  },
  "attributes": Object {},
  "clientRoles": Object {},
  "id": "<masked>",
  "name": "blong-test-group-updated",
  "path": "/blong-test-group-updated",
  "realmRoles": Array [],
  "subGroupCount": 0,
  "subGroups": Array [],
}
`;

exports[
    `keycloak.test.ts > TAP > blong int-adapter > keycloak realm CRUD > getRealm > getRealm 1`
] = `
Object {
  "accessCodeLifespan": 60,
  "accessCodeLifespanLogin": 1800,
  "accessCodeLifespanUserAction": 300,
  "accessTokenLifespan": 300,
  "accessTokenLifespanForImplicitFlow": 900,
  "actionTokenGeneratedByAdminLifespan": 43200,
  "actionTokenGeneratedByUserLifespan": 300,
  "adminEventsDetailsEnabled": false,
  "adminEventsEnabled": false,
  "attributes": Object {
    "cibaAuthRequestedUserHint": "login_hint",
    "cibaBackchannelTokenDeliveryMode": "poll",
    "cibaExpiresIn": "120",
    "cibaInterval": "5",
    "oauth2DeviceCodeLifespan": "600",
    "oauth2DevicePollingInterval": "5",
    "parRequestUriLifespan": "60",
    "realmReusableOtpCode": "false",
  },
  "browserFlow": "browser",
  "browserSecurityHeaders": Object {
    "contentSecurityPolicy": "frame-src 'self'; frame-ancestors 'self'; object-src 'none';",
    "contentSecurityPolicyReportOnly": "",
    "referrerPolicy": "no-referrer",
    "strictTransportSecurity": "max-age=31536000; includeSubDomains",
    "xContentTypeOptions": "nosniff",
    "xFrameOptions": "SAMEORIGIN",
    "xRobotsTag": "none",
    "xXSSProtection": "1; mode=block",
  },
  "bruteForceProtected": false,
  "clientAuthenticationFlow": "clients",
  "clientOfflineSessionIdleTimeout": 0,
  "clientOfflineSessionMaxLifespan": 0,
  "clientPolicies": Object {
    "policies": Array [],
  },
  "clientProfiles": Object {
    "profiles": Array [],
  },
  "clientSessionIdleTimeout": 0,
  "clientSessionMaxLifespan": 0,
  "defaultRole": Object {
    "clientRole": false,
    "composite": true,
    "containerId": "<masked>",
    "description": "\${role_default-roles}",
    "id": "<masked>",
    "name": "default-roles-blong-test-realm",
  },
  "defaultSignatureAlgorithm": "RS256",
  "directGrantFlow": "direct grant",
  "displayName": "Blong Test Realm",
  "dockerAuthenticationFlow": "docker auth",
  "duplicateEmailsAllowed": false,
  "editUsernameAllowed": false,
  "enabled": true,
  "enabledEventTypes": Array [],
  "eventsEnabled": false,
  "eventsListeners": Array [
    "jboss-logging",
  ],
  "failureFactor": 30,
  "id": "<masked>",
  "identityProviderMappers": Array [],
  "identityProviders": Array [],
  "internationalizationEnabled": false,
  "loginWithEmailAllowed": true,
  "maxDeltaTimeSeconds": 43200,
  "maxFailureWaitSeconds": 900,
  "minimumQuickLoginWaitSeconds": 60,
  "notBefore": 0,
  "oauth2DeviceCodeLifespan": 600,
  "oauth2DevicePollingInterval": 5,
  "offlineSessionIdleTimeout": 2592000,
  "offlineSessionMaxLifespan": 5184000,
  "offlineSessionMaxLifespanEnabled": false,
  "otpPolicyAlgorithm": "HmacSHA1",
  "otpPolicyCodeReusable": false,
  "otpPolicyDigits": 6,
  "otpPolicyInitialCounter": 0,
  "otpPolicyLookAheadWindow": 1,
  "otpPolicyPeriod": 30,
  "otpPolicyType": "totp",
  "otpSupportedApplications": Array [
    "totpAppFreeOTPName",
    "totpAppGoogleName",
    "totpAppMicrosoftAuthenticatorName",
  ],
  "permanentLockout": false,
  "quickLoginCheckMilliSeconds": 1000,
  "realm": "blong-test-realm",
  "refreshTokenMaxReuse": 0,
  "registrationAllowed": false,
  "registrationEmailAsUsername": false,
  "registrationFlow": "registration",
  "rememberMe": false,
  "requiredCredentials": Array [
    "password",
  ],
  "resetCredentialsFlow": "reset credentials",
  "resetPasswordAllowed": false,
  "revokeRefreshToken": false,
  "smtpServer": Object {},
  "sslRequired": "external",
  "ssoSessionIdleTimeout": 1800,
  "ssoSessionIdleTimeoutRememberMe": 0,
  "ssoSessionMaxLifespan": 36000,
  "ssoSessionMaxLifespanRememberMe": 0,
  "supportedLocales": Array [],
  "userManagedAccessAllowed": false,
  "verifyEmail": false,
  "waitIncrementSeconds": 60,
  "webAuthnPolicyAcceptableAaguids": Array [],
  "webAuthnPolicyAttestationConveyancePreference": "not specified",
  "webAuthnPolicyAuthenticatorAttachment": "not specified",
  "webAuthnPolicyAvoidSameAuthenticatorRegister": false,
  "webAuthnPolicyCreateTimeout": 0,
  "webAuthnPolicyExtraOrigins": Array [],
  "webAuthnPolicyPasswordlessAcceptableAaguids": Array [],
  "webAuthnPolicyPasswordlessAttestationConveyancePreference": "not specified",
  "webAuthnPolicyPasswordlessAuthenticatorAttachment": "not specified",
  "webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister": false,
  "webAuthnPolicyPasswordlessCreateTimeout": 0,
  "webAuthnPolicyPasswordlessExtraOrigins": Array [],
  "webAuthnPolicyPasswordlessRequireResidentKey": "not specified",
  "webAuthnPolicyPasswordlessRpEntityName": "keycloak",
  "webAuthnPolicyPasswordlessRpId": "",
  "webAuthnPolicyPasswordlessSignatureAlgorithms": Array [
    "ES256",
  ],
  "webAuthnPolicyPasswordlessUserVerificationRequirement": "not specified",
  "webAuthnPolicyRequireResidentKey": "not specified",
  "webAuthnPolicyRpEntityName": "keycloak",
  "webAuthnPolicyRpId": "",
  "webAuthnPolicySignatureAlgorithms": Array [
    "ES256",
  ],
  "webAuthnPolicyUserVerificationRequirement": "not specified",
}
`;

exports[
    `keycloak.test.ts > TAP > blong int-adapter > keycloak realm CRUD > realm-read-snapshots 1`
] = `
Object {
  "getRealm": Object {
    "accessCodeLifespan": 60,
    "accessCodeLifespanLogin": 1800,
    "accessCodeLifespanUserAction": 300,
    "accessTokenLifespan": 300,
    "accessTokenLifespanForImplicitFlow": 900,
    "actionTokenGeneratedByAdminLifespan": 43200,
    "actionTokenGeneratedByUserLifespan": 300,
    "adminEventsDetailsEnabled": false,
    "adminEventsEnabled": false,
    "attributes": Object {
      "cibaAuthRequestedUserHint": "login_hint",
      "cibaBackchannelTokenDeliveryMode": "poll",
      "cibaExpiresIn": "120",
      "cibaInterval": "5",
      "oauth2DeviceCodeLifespan": "600",
      "oauth2DevicePollingInterval": "5",
      "parRequestUriLifespan": "60",
      "realmReusableOtpCode": "false",
    },
    "browserFlow": "browser",
    "browserSecurityHeaders": Object {
      "contentSecurityPolicy": "frame-src 'self'; frame-ancestors 'self'; object-src 'none';",
      "contentSecurityPolicyReportOnly": "",
      "referrerPolicy": "no-referrer",
      "strictTransportSecurity": "max-age=31536000; includeSubDomains",
      "xContentTypeOptions": "nosniff",
      "xFrameOptions": "SAMEORIGIN",
      "xRobotsTag": "none",
      "xXSSProtection": "1; mode=block",
    },
    "bruteForceProtected": false,
    "clientAuthenticationFlow": "clients",
    "clientOfflineSessionIdleTimeout": 0,
    "clientOfflineSessionMaxLifespan": 0,
    "clientPolicies": Object {
      "policies": Array [],
    },
    "clientProfiles": Object {
      "profiles": Array [],
    },
    "clientSessionIdleTimeout": 0,
    "clientSessionMaxLifespan": 0,
    "defaultRole": Object {
      "clientRole": false,
      "composite": true,
      "containerId": "<masked>",
      "description": "\${role_default-roles}",
      "id": "<masked>",
      "name": "default-roles-blong-test-realm",
    },
    "defaultSignatureAlgorithm": "RS256",
    "directGrantFlow": "direct grant",
    "displayName": "Blong Test Realm",
    "dockerAuthenticationFlow": "docker auth",
    "duplicateEmailsAllowed": false,
    "editUsernameAllowed": false,
    "enabled": true,
    "enabledEventTypes": Array [],
    "eventsEnabled": false,
    "eventsListeners": Array [
      "jboss-logging",
    ],
    "failureFactor": 30,
    "id": "<masked>",
    "identityProviderMappers": Array [],
    "identityProviders": Array [],
    "internationalizationEnabled": false,
    "loginWithEmailAllowed": true,
    "maxDeltaTimeSeconds": 43200,
    "maxFailureWaitSeconds": 900,
    "minimumQuickLoginWaitSeconds": 60,
    "notBefore": 0,
    "oauth2DeviceCodeLifespan": 600,
    "oauth2DevicePollingInterval": 5,
    "offlineSessionIdleTimeout": 2592000,
    "offlineSessionMaxLifespan": 5184000,
    "offlineSessionMaxLifespanEnabled": false,
    "otpPolicyAlgorithm": "HmacSHA1",
    "otpPolicyCodeReusable": false,
    "otpPolicyDigits": 6,
    "otpPolicyInitialCounter": 0,
    "otpPolicyLookAheadWindow": 1,
    "otpPolicyPeriod": 30,
    "otpPolicyType": "totp",
    "otpSupportedApplications": Array [
      "totpAppFreeOTPName",
      "totpAppGoogleName",
      "totpAppMicrosoftAuthenticatorName",
    ],
    "permanentLockout": false,
    "quickLoginCheckMilliSeconds": 1000,
    "realm": "blong-test-realm",
    "refreshTokenMaxReuse": 0,
    "registrationAllowed": false,
    "registrationEmailAsUsername": false,
    "registrationFlow": "registration",
    "rememberMe": false,
    "requiredCredentials": Array [
      "password",
    ],
    "resetCredentialsFlow": "reset credentials",
    "resetPasswordAllowed": false,
    "revokeRefreshToken": false,
    "smtpServer": Object {},
    "sslRequired": "external",
    "ssoSessionIdleTimeout": 1800,
    "ssoSessionIdleTimeoutRememberMe": 0,
    "ssoSessionMaxLifespan": 36000,
    "ssoSessionMaxLifespanRememberMe": 0,
    "supportedLocales": Array [],
    "userManagedAccessAllowed": false,
    "verifyEmail": false,
    "waitIncrementSeconds": 60,
    "webAuthnPolicyAcceptableAaguids": Array [],
    "webAuthnPolicyAttestationConveyancePreference": "not specified",
    "webAuthnPolicyAuthenticatorAttachment": "not specified",
    "webAuthnPolicyAvoidSameAuthenticatorRegister": false,
    "webAuthnPolicyCreateTimeout": 0,
    "webAuthnPolicyExtraOrigins": Array [],
    "webAuthnPolicyPasswordlessAcceptableAaguids": Array [],
    "webAuthnPolicyPasswordlessAttestationConveyancePreference": "not specified",
    "webAuthnPolicyPasswordlessAuthenticatorAttachment": "not specified",
    "webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister": false,
    "webAuthnPolicyPasswordlessCreateTimeout": 0,
    "webAuthnPolicyPasswordlessExtraOrigins": Array [],
    "webAuthnPolicyPasswordlessRequireResidentKey": "not specified",
    "webAuthnPolicyPasswordlessRpEntityName": "keycloak",
    "webAuthnPolicyPasswordlessRpId": "",
    "webAuthnPolicyPasswordlessSignatureAlgorithms": Array [
      "ES256",
    ],
    "webAuthnPolicyPasswordlessUserVerificationRequirement": "not specified",
    "webAuthnPolicyRequireResidentKey": "not specified",
    "webAuthnPolicyRpEntityName": "keycloak",
    "webAuthnPolicyRpId": "",
    "webAuthnPolicySignatureAlgorithms": Array [
      "ES256",
    ],
    "webAuthnPolicyUserVerificationRequirement": "not specified",
  },
  "verifyEdit": Object {
    "accessCodeLifespan": 60,
    "accessCodeLifespanLogin": 1800,
    "accessCodeLifespanUserAction": 300,
    "accessTokenLifespan": 300,
    "accessTokenLifespanForImplicitFlow": 900,
    "actionTokenGeneratedByAdminLifespan": 43200,
    "actionTokenGeneratedByUserLifespan": 300,
    "adminEventsDetailsEnabled": false,
    "adminEventsEnabled": false,
    "attributes": Object {
      "cibaAuthRequestedUserHint": "login_hint",
      "cibaBackchannelTokenDeliveryMode": "poll",
      "cibaExpiresIn": "120",
      "cibaInterval": "5",
      "oauth2DeviceCodeLifespan": "600",
      "oauth2DevicePollingInterval": "5",
      "parRequestUriLifespan": "60",
      "realmReusableOtpCode": "false",
    },
    "browserFlow": "browser",
    "browserSecurityHeaders": Object {
      "contentSecurityPolicy": "frame-src 'self'; frame-ancestors 'self'; object-src 'none';",
      "contentSecurityPolicyReportOnly": "",
      "referrerPolicy": "no-referrer",
      "strictTransportSecurity": "max-age=31536000; includeSubDomains",
      "xContentTypeOptions": "nosniff",
      "xFrameOptions": "SAMEORIGIN",
      "xRobotsTag": "none",
      "xXSSProtection": "1; mode=block",
    },
    "bruteForceProtected": false,
    "clientAuthenticationFlow": "clients",
    "clientOfflineSessionIdleTimeout": 0,
    "clientOfflineSessionMaxLifespan": 0,
    "clientPolicies": Object {
      "policies": Array [],
    },
    "clientProfiles": Object {
      "profiles": Array [],
    },
    "clientSessionIdleTimeout": 0,
    "clientSessionMaxLifespan": 0,
    "defaultRole": Object {
      "clientRole": false,
      "composite": true,
      "containerId": "<masked>",
      "description": "\${role_default-roles}",
      "id": "<masked>",
      "name": "default-roles-blong-test-realm",
    },
    "defaultSignatureAlgorithm": "RS256",
    "directGrantFlow": "direct grant",
    "displayName": "Blong Test Realm Updated",
    "dockerAuthenticationFlow": "docker auth",
    "duplicateEmailsAllowed": false,
    "editUsernameAllowed": false,
    "enabled": true,
    "enabledEventTypes": Array [],
    "eventsEnabled": false,
    "eventsListeners": Array [
      "jboss-logging",
    ],
    "failureFactor": 30,
    "id": "<masked>",
    "identityProviderMappers": Array [],
    "identityProviders": Array [],
    "internationalizationEnabled": false,
    "loginWithEmailAllowed": true,
    "maxDeltaTimeSeconds": 43200,
    "maxFailureWaitSeconds": 900,
    "minimumQuickLoginWaitSeconds": 60,
    "notBefore": 0,
    "oauth2DeviceCodeLifespan": 600,
    "oauth2DevicePollingInterval": 5,
    "offlineSessionIdleTimeout": 2592000,
    "offlineSessionMaxLifespan": 5184000,
    "offlineSessionMaxLifespanEnabled": false,
    "otpPolicyAlgorithm": "HmacSHA1",
    "otpPolicyCodeReusable": false,
    "otpPolicyDigits": 6,
    "otpPolicyInitialCounter": 0,
    "otpPolicyLookAheadWindow": 1,
    "otpPolicyPeriod": 30,
    "otpPolicyType": "totp",
    "otpSupportedApplications": Array [
      "totpAppFreeOTPName",
      "totpAppGoogleName",
      "totpAppMicrosoftAuthenticatorName",
    ],
    "permanentLockout": false,
    "quickLoginCheckMilliSeconds": 1000,
    "realm": "blong-test-realm",
    "refreshTokenMaxReuse": 0,
    "registrationAllowed": false,
    "registrationEmailAsUsername": false,
    "registrationFlow": "registration",
    "rememberMe": false,
    "requiredCredentials": Array [
      "password",
    ],
    "resetCredentialsFlow": "reset credentials",
    "resetPasswordAllowed": false,
    "revokeRefreshToken": false,
    "smtpServer": Object {},
    "sslRequired": "external",
    "ssoSessionIdleTimeout": 1800,
    "ssoSessionIdleTimeoutRememberMe": 0,
    "ssoSessionMaxLifespan": 36000,
    "ssoSessionMaxLifespanRememberMe": 0,
    "supportedLocales": Array [],
    "userManagedAccessAllowed": false,
    "verifyEmail": false,
    "waitIncrementSeconds": 60,
    "webAuthnPolicyAcceptableAaguids": Array [],
    "webAuthnPolicyAttestationConveyancePreference": "not specified",
    "webAuthnPolicyAuthenticatorAttachment": "not specified",
    "webAuthnPolicyAvoidSameAuthenticatorRegister": false,
    "webAuthnPolicyCreateTimeout": 0,
    "webAuthnPolicyExtraOrigins": Array [],
    "webAuthnPolicyPasswordlessAcceptableAaguids": Array [],
    "webAuthnPolicyPasswordlessAttestationConveyancePreference": "not specified",
    "webAuthnPolicyPasswordlessAuthenticatorAttachment": "not specified",
    "webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister": false,
    "webAuthnPolicyPasswordlessCreateTimeout": 0,
    "webAuthnPolicyPasswordlessExtraOrigins": Array [],
    "webAuthnPolicyPasswordlessRequireResidentKey": "not specified",
    "webAuthnPolicyPasswordlessRpEntityName": "keycloak",
    "webAuthnPolicyPasswordlessRpId": "",
    "webAuthnPolicyPasswordlessSignatureAlgorithms": Array [
      "ES256",
    ],
    "webAuthnPolicyPasswordlessUserVerificationRequirement": "not specified",
    "webAuthnPolicyRequireResidentKey": "not specified",
    "webAuthnPolicyRpEntityName": "keycloak",
    "webAuthnPolicyRpId": "",
    "webAuthnPolicySignatureAlgorithms": Array [
      "ES256",
    ],
    "webAuthnPolicyUserVerificationRequirement": "not specified",
  },
}
`;

exports[
    `keycloak.test.ts > TAP > blong int-adapter > keycloak realm CRUD > verifyEdit > verifyEdit 1`
] = `
Object {
  "accessCodeLifespan": 60,
  "accessCodeLifespanLogin": 1800,
  "accessCodeLifespanUserAction": 300,
  "accessTokenLifespan": 300,
  "accessTokenLifespanForImplicitFlow": 900,
  "actionTokenGeneratedByAdminLifespan": 43200,
  "actionTokenGeneratedByUserLifespan": 300,
  "adminEventsDetailsEnabled": false,
  "adminEventsEnabled": false,
  "attributes": Object {
    "cibaAuthRequestedUserHint": "login_hint",
    "cibaBackchannelTokenDeliveryMode": "poll",
    "cibaExpiresIn": "120",
    "cibaInterval": "5",
    "oauth2DeviceCodeLifespan": "600",
    "oauth2DevicePollingInterval": "5",
    "parRequestUriLifespan": "60",
    "realmReusableOtpCode": "false",
  },
  "browserFlow": "browser",
  "browserSecurityHeaders": Object {
    "contentSecurityPolicy": "frame-src 'self'; frame-ancestors 'self'; object-src 'none';",
    "contentSecurityPolicyReportOnly": "",
    "referrerPolicy": "no-referrer",
    "strictTransportSecurity": "max-age=31536000; includeSubDomains",
    "xContentTypeOptions": "nosniff",
    "xFrameOptions": "SAMEORIGIN",
    "xRobotsTag": "none",
    "xXSSProtection": "1; mode=block",
  },
  "bruteForceProtected": false,
  "clientAuthenticationFlow": "clients",
  "clientOfflineSessionIdleTimeout": 0,
  "clientOfflineSessionMaxLifespan": 0,
  "clientPolicies": Object {
    "policies": Array [],
  },
  "clientProfiles": Object {
    "profiles": Array [],
  },
  "clientSessionIdleTimeout": 0,
  "clientSessionMaxLifespan": 0,
  "defaultRole": Object {
    "clientRole": false,
    "composite": true,
    "containerId": "<masked>",
    "description": "\${role_default-roles}",
    "id": "<masked>",
    "name": "default-roles-blong-test-realm",
  },
  "defaultSignatureAlgorithm": "RS256",
  "directGrantFlow": "direct grant",
  "displayName": "Blong Test Realm Updated",
  "dockerAuthenticationFlow": "docker auth",
  "duplicateEmailsAllowed": false,
  "editUsernameAllowed": false,
  "enabled": true,
  "enabledEventTypes": Array [],
  "eventsEnabled": false,
  "eventsListeners": Array [
    "jboss-logging",
  ],
  "failureFactor": 30,
  "id": "<masked>",
  "identityProviderMappers": Array [],
  "identityProviders": Array [],
  "internationalizationEnabled": false,
  "loginWithEmailAllowed": true,
  "maxDeltaTimeSeconds": 43200,
  "maxFailureWaitSeconds": 900,
  "minimumQuickLoginWaitSeconds": 60,
  "notBefore": 0,
  "oauth2DeviceCodeLifespan": 600,
  "oauth2DevicePollingInterval": 5,
  "offlineSessionIdleTimeout": 2592000,
  "offlineSessionMaxLifespan": 5184000,
  "offlineSessionMaxLifespanEnabled": false,
  "otpPolicyAlgorithm": "HmacSHA1",
  "otpPolicyCodeReusable": false,
  "otpPolicyDigits": 6,
  "otpPolicyInitialCounter": 0,
  "otpPolicyLookAheadWindow": 1,
  "otpPolicyPeriod": 30,
  "otpPolicyType": "totp",
  "otpSupportedApplications": Array [
    "totpAppFreeOTPName",
    "totpAppGoogleName",
    "totpAppMicrosoftAuthenticatorName",
  ],
  "permanentLockout": false,
  "quickLoginCheckMilliSeconds": 1000,
  "realm": "blong-test-realm",
  "refreshTokenMaxReuse": 0,
  "registrationAllowed": false,
  "registrationEmailAsUsername": false,
  "registrationFlow": "registration",
  "rememberMe": false,
  "requiredCredentials": Array [
    "password",
  ],
  "resetCredentialsFlow": "reset credentials",
  "resetPasswordAllowed": false,
  "revokeRefreshToken": false,
  "smtpServer": Object {},
  "sslRequired": "external",
  "ssoSessionIdleTimeout": 1800,
  "ssoSessionIdleTimeoutRememberMe": 0,
  "ssoSessionMaxLifespan": 36000,
  "ssoSessionMaxLifespanRememberMe": 0,
  "supportedLocales": Array [],
  "userManagedAccessAllowed": false,
  "verifyEmail": false,
  "waitIncrementSeconds": 60,
  "webAuthnPolicyAcceptableAaguids": Array [],
  "webAuthnPolicyAttestationConveyancePreference": "not specified",
  "webAuthnPolicyAuthenticatorAttachment": "not specified",
  "webAuthnPolicyAvoidSameAuthenticatorRegister": false,
  "webAuthnPolicyCreateTimeout": 0,
  "webAuthnPolicyExtraOrigins": Array [],
  "webAuthnPolicyPasswordlessAcceptableAaguids": Array [],
  "webAuthnPolicyPasswordlessAttestationConveyancePreference": "not specified",
  "webAuthnPolicyPasswordlessAuthenticatorAttachment": "not specified",
  "webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister": false,
  "webAuthnPolicyPasswordlessCreateTimeout": 0,
  "webAuthnPolicyPasswordlessExtraOrigins": Array [],
  "webAuthnPolicyPasswordlessRequireResidentKey": "not specified",
  "webAuthnPolicyPasswordlessRpEntityName": "keycloak",
  "webAuthnPolicyPasswordlessRpId": "",
  "webAuthnPolicyPasswordlessSignatureAlgorithms": Array [
    "ES256",
  ],
  "webAuthnPolicyPasswordlessUserVerificationRequirement": "not specified",
  "webAuthnPolicyRequireResidentKey": "not specified",
  "webAuthnPolicyRpEntityName": "keycloak",
  "webAuthnPolicyRpId": "",
  "webAuthnPolicySignatureAlgorithms": Array [
    "ES256",
  ],
  "webAuthnPolicyUserVerificationRequirement": "not specified",
}
`;

exports[`keycloak.test.ts > TAP > blong int-adapter > keycloak role CRUD > getRole > getRole 1`] = `
Object {
  "attributes": Object {},
  "clientRole": false,
  "composite": false,
  "containerId": "<masked>",
  "description": "Blong integration test role",
  "id": "<masked>",
  "name": "blong-test-role",
}
`;

exports[`keycloak.test.ts > TAP > blong int-adapter > keycloak role CRUD > role-read-snapshots 1`] =
    `
Object {
  "getRole": Object {
    "attributes": Object {},
    "clientRole": false,
    "composite": false,
    "containerId": "<masked>",
    "description": "Blong integration test role",
    "id": "<masked>",
    "name": "blong-test-role",
  },
  "verifyEdit": Object {
    "attributes": Object {},
    "clientRole": false,
    "composite": false,
    "containerId": "<masked>",
    "description": "Updated description for blong test role",
    "id": "<masked>",
    "name": "blong-test-role",
  },
}
`;

exports[
    `keycloak.test.ts > TAP > blong int-adapter > keycloak role CRUD > verifyEdit > verifyEdit 1`
] = `
Object {
  "attributes": Object {},
  "clientRole": false,
  "composite": false,
  "containerId": "<masked>",
  "description": "Updated description for blong test role",
  "id": "<masked>",
  "name": "blong-test-role",
}
`;

exports[`keycloak.test.ts > TAP > blong int-adapter > keycloak user CRUD > getUser > getUser 1`] = `
Object {
  "access": Object {
    "impersonate": true,
    "manage": true,
    "manageGroupMembership": true,
    "mapRoles": true,
    "view": true,
  },
  "createdTimestamp": "<masked>",
  "disableableCredentialTypes": Array [],
  "email": "blong-test-crud@test.com",
  "emailVerified": true,
  "enabled": true,
  "firstName": "Blong",
  "id": "<masked>",
  "lastName": "Test",
  "notBefore": 0,
  "requiredActions": Array [],
  "totp": false,
  "username": "blong-test-crud",
}
`;

exports[`keycloak.test.ts > TAP > blong int-adapter > keycloak user CRUD > user-read-snapshots 1`] =
    `
Object {
  "getUser": Object {
    "access": Object {
      "impersonate": true,
      "manage": true,
      "manageGroupMembership": true,
      "mapRoles": true,
      "view": true,
    },
    "createdTimestamp": "<masked>",
    "disableableCredentialTypes": Array [],
    "email": "blong-test-crud@test.com",
    "emailVerified": true,
    "enabled": true,
    "firstName": "Blong",
    "id": "<masked>",
    "lastName": "Test",
    "notBefore": 0,
    "requiredActions": Array [],
    "totp": false,
    "username": "blong-test-crud",
  },
  "verifyEdit": Object {
    "access": Object {
      "impersonate": true,
      "manage": true,
      "manageGroupMembership": true,
      "mapRoles": true,
      "view": true,
    },
    "createdTimestamp": "<masked>",
    "disableableCredentialTypes": Array [],
    "email": "blong-test-crud@test.com",
    "emailVerified": true,
    "enabled": true,
    "firstName": "Blong Updated",
    "id": "<masked>",
    "lastName": "Test Updated",
    "notBefore": 0,
    "requiredActions": Array [],
    "totp": false,
    "username": "blong-test-crud",
  },
}
`;

exports[
    `keycloak.test.ts > TAP > blong int-adapter > keycloak user CRUD > verifyEdit > verifyEdit 1`
] = `
Object {
  "access": Object {
    "impersonate": true,
    "manage": true,
    "manageGroupMembership": true,
    "mapRoles": true,
    "view": true,
  },
  "createdTimestamp": "<masked>",
  "disableableCredentialTypes": Array [],
  "email": "blong-test-crud@test.com",
  "emailVerified": true,
  "enabled": true,
  "firstName": "Blong Updated",
  "id": "<masked>",
  "lastName": "Test Updated",
  "notBefore": 0,
  "requiredActions": Array [],
  "totp": false,
  "username": "blong-test-crud",
}
`;
