import { library } from '@feasibleone/blong';

export default library(({lib: {error}}) => ({
    errors: error({
        'payshield.parser.header': 'Cant parse header pattern!',
        'payshield.parser.request': 'Cant parse request pattern for command: {command}!',
        'payshield.parser.response': 'Cant parse response pattern for command: {command}!',
        'payshield.parser.body': 'Unable to build body of opcode: {command}!',
        'payshield.unableMatchingHeaderPattern': 'Unable to match header to header pattern!',
        'payshield.unableMatchingResponseECode': 'Unable to match response errorCode!',
        'payshield.unknownResponseCode': 'Unknown response code: {code}',
        'payshield.notImplemented': 'Not implemented opcode: {opcode}',
        'payshield.unableMatchingPattern': 'Unable to match pattern for opcode: {opcode}',

        'payshield.01': 'Verification failure or warning of imported key parity error',
        'payshield.generateArqc3.01': 'ARQC/TC/AAC verification failed',
        'payshield.generateArqc4.01': 'ARQC/TC/AAC/MPVV verification failure',
        'payshield.generateVerifyMacDukpt.01': 'MAC Verification Failure',
        'payshield.verifyCvv.01': 'CVV failed verification',
        'payshield.verifyInterPinIbm.01': 'PIN verification failure',
        'payshield.verifyInterPinPvv.01': 'PIN verification failure',
        'payshield.verifyMac.01': 'MAC verification failed',
        'payshield.verifyOffsetIbmDukpt.01': 'PIN Verification failure',
        'payshield.verifyPinGenerateOffset.01': 'PIN verification failure',
        'payshield.verifyPinGeneratePvv.01': 'PIN Verification failure',
        'payshield.verifyPvvDukpt.01': 'PIN Verification failure',
        'payshield.verifyTermPinIbm.01': 'PIN Verification failure',
        'payshield.verifyTermPinPvv.01': 'PIN verification failure',

        'payshield.decryptDataBlock.02': 'Invalid Mode Flag field',
        'payshield.encryptDataBlock.02': 'Invalid Mode Flag field',
        'payshield.generateMac.02': 'Invalid Mode Flag field',
        'payshield.translateDataBlock.02': 'Invalid Mode Flag field',
        'payshield.verifyMac.02': 'Invalid Mode Flag field',

        'payshield.decryptDataBlock.03': 'Invalid Input Format Flag field',
        'payshield.encryptDataBlock.03': 'Invalid Input Format Flag field',
        'payshield.formKeyFromComponents.03': 'Invalid number of components',
        'payshield.generateArqc3.03': 'Mode = 3 or 4 but Scheme ID ≠ 0',
        'payshield.generateMac.03': 'Invalid Input Format Flag field',
        'payshield.generateOffsetIbm.03': 'Excluded PIN count incorrect',
        'payshield.generateRsaKeyPair.03': 'Invalid public key encoding type',
        'payshield.generateRsaSignature.03': 'Invalid private key type',
        'payshield.translateDataBlock.03': 'Invalid Input Format Flag field',
        'payshield.verifyMac.03': 'Invalid Input Format Flag field',

        'payshield.04': 'Invalid key type code',
        'payshield.decryptDataBlock.04': 'Invalid Output Format Flag field',
        'payshield.encryptDataBlock.04': 'Invalid Output Format Flag field',
        'payshield.generateArqc3.04': 'Invalid Mode value',
        'payshield.generateArqc4.04': 'Unrecognized Mode Flag',
        'payshield.generateMac.04': 'Invalid MAC Algorithm field',
        'payshield.generateRsaKeyPair.04': 'Key Length error',
        'payshield.generateRsaSignature.04': 'Invalid private key flag',
        'payshield.translateDataBlock.04': 'Invalid Output Format Flag field',
        'payshield.translateKeyLmkLmk.04': 'Invalid key type code',
        'payshield.verifyMac.04': 'Invalid MAC Algorithm field',

        'payshield.05': 'Invalid key length flag',
        'payshield.decryptDataBlock.05': 'Invalid Key Type field',
        'payshield.encryptDataBlock.05': 'Invalid Key Type field',
        'payshield.generateArqc3.05': 'Unrecognized Scheme ID',
        'payshield.generateArqc4.05': 'Unrecognized Scheme ID',
        'payshield.generateMac.05': 'Invalid Key Type field',
        'payshield.generateRsaKeyPair.05': 'Invalid key type',
        'payshield.generateRsaSignature.05': 'Invalid hash identifier',
        'payshield.hashDataBlock.05': 'Invalid hash identifier',
        'payshield.translateDataBlock.05': 'Invalid Key Type field',
        'payshield.translateKeyLmkLmk.05': 'Invalid key length flag',
        'payshield.verifyMac.05': 'Invalid Key Type field',

        'payshield.decryptDataBlock.06': 'Invalid Message Length field',
        'payshield.encryptDataBlock.06': 'Invalid Message Length field',
        'payshield.generateArqc3.06': 'Discretionary MAC verification failed',
        'payshield.generateArqc4.06': 'Invalid YHHHHCC value',
        'payshield.generateMac.06': 'Invalid Message Length field',
        'payshield.generateRsaKeyPair.06': 'Public exponent length error',
        'payshield.generateRsaSignature.06': 'Invalid signature identifier',
        'payshield.translateDataBlock.06': 'Actual Message Length is too Short',
        'payshield.verifyMac.06': 'Invalid Message Length field',

        'payshield.generateRsaSignature.07': 'Invalid pad mode identifier',
        'payshield.translateDataBlock.07': 'Invalid Destination Mode Flag Field',

        'payshield.generateRsaKeyPair.08': 'Supplied public exponent is even',
        'payshield.translateDataBlock.08': 'Invalid destination Key Type Field',

        'payshield.generateMac.09': 'Invalid Padding Method field',
        'payshield.verifyMac.09': 'Invalid Padding Method field',

        'payshield.10': 'Source key parity error',
        'payshield.generateKey.10': 'ZMK or TMK Parity error',
        'payshield.formKeyFromComponents.10': 'Component parity error',
        'payshield.importKey.10': 'ZMK Parity error',
        'payshield.exportKey.10': 'ZMK or TMK Parity error',
        'payshield.generateOffsetIbm.10': 'TPK or ZPK parity error',
        'payshield.generateKeyCheckValue.10': 'Key parity error',
        'payshield.translateKeyLmkLmk.10': 'Key parity error',
        'payshield.translatePinTpkZpk.10': 'Source TPK parity error',
        'payshield.translatePinZpkZpk.10': 'Source ZPK parity error',
        'payshield.verifyPinGeneratePvv.10': 'PIN Block Key parity error',
        'payshield.generateCvv.10': 'CVK A or CVK B parity error',
        'payshield.verifyCvv.10': 'CVK A or B parity error',
        'payshield.verifyTermPinIbm.10': 'TPK parity error',
        'payshield.verifyTermPinPvv.10': 'TPK parity error',
        'payshield.generateOffsetIbmLmk.10': 'PVK parity error',
        'payshield.generatePvvLmk.10': 'PVK parity error',
        'payshield.verifyPinGenerateOffset.10': 'PIN Block Key parity error',
        'payshield.verifyInterPinIbm.10': 'ZPK parity error',
        'payshield.verifyInterPinPvv.10': 'ZPK parity error',
        'payshield.derivePinIbm.10': 'PVK parity error',
        'payshield.generatePvv.10': 'PVK parity error',
        'payshield.translatePinBdkBdkZpk.10': 'BDK parity error',
        'payshield.verifyOffsetIbmDukpt.10': 'BDK parity error',
        'payshield.verifyPvvDukpt.10': 'BDK parity error',
        'payshield.translatePinTpkLmk.10': 'TPK parity error',
        'payshield.translatePinZpkLmk.10': 'ZPK parity error',
        'payshield.generateArqc3.10': 'MK-AC parity error',
        'payshield.generateArqc4.10': 'MK parity error',
        'payshield.encryptDataBlock.10': 'Encryption Key Parity Error',
        'payshield.decryptDataBlock.10': 'Decryption Key Parity Error',
        'payshield.translateDataBlock.10': 'Decryption Key Parity Error',
        'payshield.generateMac.10': 'MAC Key Parity Error',
        'payshield.verifyMac.10': 'MAC Key Parity Error',
        'payshield.printTmkMailer.10': 'TMK parity error',

        'payshield.11': 'Destination key parity error or key all zeros',
        'payshield.exportKey.11': 'Key parity error',
        'payshield.generateOffsetIbm.11': 'PVK parity error',
        'payshield.translatePinTpkZpk.11': 'Destination ZPK parity error',
        'payshield.translatePinZpkZpk.11': 'Destination ZPK parity error',
        'payshield.verifyPinGeneratePvv.11': 'PVK parity error',
        'payshield.verifyTermPinIbm.11': 'PVK parity error',
        'payshield.verifyTermPinPvv.11': 'PVK parity error',
        'payshield.verifyPinGenerateOffset.11': 'PVK parity error',
        'payshield.verifyInterPinIbm.11': 'PVK parity error',
        'payshield.verifyInterPinPvv.11': 'PVK parity error',
        'payshield.translatePinBdkBdkZpk.11': 'Interchange key parity error',
        'payshield.verifyOffsetIbmDukpt.11': 'PVK error',
        'payshield.verifyPvvDukpt.11': 'PVK error',
        'payshield.translatePinLmkZpk.11': 'ZPK parity error',
        'payshield.generateArqc3.11': 'MK-SMI parity error',
        'payshield.translateDataBlock.11': 'Encryption Key Parity Error',

        'payshield.12': 'Contents of user storage not available. Reset, power-down or overwrite',
        'payshield.13': 'Invalid LMK Identifier',
        'payshield.14': 'PIN encrypted under LMK pair 02-03 is invalid',

        'payshield.15': 'Invalid input data (invalid format, invalid characters, or not enough data provided)',
        'payshield.translateDataBlock.15': 'Actual Message Length is too Long',

        'payshield.16': 'Console or printer not ready or not connected',
        'payshield.printPinEnd.16': 'Printer not ready/disconnected',
        'payshield.printTmkMailerEnd.16': 'Printer time out',

        'payshield.17': 'HSM not in the Authorized state, or not enabled for clear PIN output, or both',
        'payshield.18': 'Document format definition not loaded',
        'payshield.19': 'Specified Diebold Table is invalid',
        'payshield.20': 'PIN block does not contain valid values',
        'payshield.21': 'Invalid index value, or index/block count would cause an overflow condition',
        'payshield.22': 'Invalid account number',
        'payshield.23': 'Invalid PIN block format code',
        'payshield.24': 'PIN is fewer than 4 or more than 12 digits in length',
        'payshield.25': 'Decimalization Table error',
        'payshield.26': 'Invalid key scheme',

        'payshield.27': 'Incompatible key length',
        'payshield.generateCvv.27': 'CVK not double length',
        'payshield.generatePvv.27': 'PVK not double length',
        'payshield.generatePvvLmk.27': 'PVK not double length',
        'payshield.translatePinBdkBdkZpk.27': 'BDK not double or triple length',
        'payshield.verifyCvv.27': 'CVK not double length',
        'payshield.verifyInterPinPvv.27': 'PVK not double length',
        'payshield.verifyOffsetIbmDukpt.27': 'BDK not double length',
        'payshield.verifyPinGeneratePvv.27': 'PVK not double length',
        'payshield.verifyPvvDukpt.27': 'BDK not double or triple length',
        'payshield.verifyTermPinPvv.27': 'PVK not double length',

        'payshield.28': 'Invalid key type',
        'payshield.29': 'Key function not permitted',
        'payshield.30': 'Invalid reference number',
        'payshield.31': 'Insufficient solicitation entries for batch',
        'payshield.33': 'LMK key change storage is corrupted',
        'payshield.35': 'Illegal Message Format',
        'payshield.39': 'Fraud detection',
        'payshield.40': 'Invalid checksum',
        'payshield.41': 'Internal hardware/software error: bad RAM, invalid error codes, etc.',
        'payshield.42': 'DES failure',
        'payshield.44': "Migration not allowed: 'Enforce key type 002 separation for PCI HSM compliance' not set",
        'payshield.45': 'Invalid key migration destination key type',
        'payshield.47': 'Algorithm not licensed',
        'payshield.48': 'Stronger LMK required to protect this size RSA key',
        'payshield.49': 'Private key error, report to supervisor',
        'payshield.51': 'Invalid message header',
        'payshield.52': 'Invalid Branch/Height',
        'payshield.65': 'Transaction Key Scheme set to None',
        'payshield.67': 'Command not licensed',
        'payshield.68': 'Command has been disabled',
        'payshield.69': 'PIN block format has been disabled',
        'payshield.74': 'Invalid digest info syntax (no hash mode only)',
        'payshield.75': 'Single length key masquerading as double or triple length key',
        'payshield.76': 'Public key length error',
        'payshield.generateRsaSignature.76': 'Hash length error',
        'payshield.77': 'Clear data block error',
        'payshield.78': 'Private key length error',
        'payshield.79': 'Hash algorithm object identifier error',

        'payshield.80': 'Data length error. The amount of MAC data (or other data) is greater than or less than the expected amount.',
        'payshield.generateArqc3.80': 'Transaction Data length error',
        'payshield.generateRsaSignature.80': 'Message length error or a standard error code.',

        'payshield.81': 'Invalid certificate header',
        'payshield.verifyPinGeneratePvv.81': 'PIN length mismatch',
        'payshield.generatePvv.81': 'PIN length mismatch',
        'payshield.generateOffsetIbm.81': 'PIN length mismatch',
        'payshield.generateOffsetIbmLmk.81': 'PIN length mismatch',
        'payshield.generatePvvLmk.81': 'PIN length mismatch',
        'payshield.verifyPinGenerateOffset.81': 'PIN length mismatch',
        'payshield.derivePinIbm.81': 'PIN length mismatch',
        'payshield.generateRandomPin.81': 'PIN length mismatch',
        'payshield.generateArqc3.81': 'Zero length Transaction Data',

        'payshield.82': 'Invalid check value length',
        'payshield.generateArqc3.82': 'Invalid Discretionary MAC Data length',

        'payshield.83': 'Key block format error',
        'payshield.84': 'Key block check value error',
        'payshield.85': 'Invalid OAEP Mask Generation Function',

        'payshield.86': 'Invalid OAEP MGF Hash Function',
        'payshield.verifyPinGeneratePvv.86': 'PIN exists in either global or local Excluded PIN Table',
        'payshield.generateOffsetIbm.86': 'PIN exists in either global or local Excluded PIN Table',
        'payshield.generateOffsetIbmLmk.86': 'PIN exists in either global or local Excluded PIN Table',
        'payshield.generatePvvLmk.86': 'PIN exists in either global or local Excluded PIN Table',
        'payshield.verifyPinGenerateOffset.86': 'PIN exists in either global or local Excluded PIN Table',
        'payshield.derivePinIbm.86': 'PIN exists in either global or local Excluded PIN Table',
        'payshield.generatePvv.86': 'PIN exists in either global or local Excluded PIN Table',

        'payshield.87': 'OAEP Parameter Error',
        'payshield.90': 'Data parity error in the request message received by the HSM',
        'payshield.91': 'Longitudinal Redundancy Check (LRC) character does not match the value computed over the input data (when the HSM has received a transparent async packet)',
        'payshield.92': 'The Count value (for the Command/Data field) is not between limits, or is not correct (when the HSM has received a transparent async packet)',
        'payshield.A1': 'Incompatible LMK schemes',
        'payshield.A2': 'Incompatible LMK identifiers',
        'payshield.A3': 'Incompatible keyblock LMK identifiers',
        'payshield.A4': 'Key block authentication failure',
        'payshield.A5': 'Incompatible key length',
        'payshield.A6': 'Invalid key usage',
        'payshield.A7': 'Invalid algorithm',
        'payshield.A8': 'Invalid mode of use',
        'payshield.A9': 'Invalid key version number',
        'payshield.AA': 'Invalid export field',
        'payshield.AB': 'Invalid number of optional blocks',
        'payshield.AC': 'Optional header block error',
        'payshield.AD': 'Key status optional block error',
        'payshield.AE': 'Invalid start date/time',
        'payshield.AF': 'Invalid end date/time',
        'payshield.B0': 'Invalid encryption mode',
        'payshield.B1': 'Invalid authentication mode',
        'payshield.B2': 'Miscellaneous keyblock error',
        'payshield.B3': 'Invalid number of optional blocks',
        'payshield.B4': 'Optional block data error',
        'payshield.B5': 'Incompatible components',
        'payshield.B6': 'Incompatible key status optional blocks',
        'payshield.B7': 'Invalid change field',
        'payshield.B8': 'Invalid old value',
        'payshield.B9': 'Invalid new value',
        'payshield.BA': 'No key status block in the keyblock',
        'payshield.BB': 'Invalid wrapping key',
        'payshield.BC': 'Repeated optional block',
        'payshield.BD': 'Incompatible key types'
    })
}));
