apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/managed-by: blong-kustomize
      app.kubernetes.io/name: blong-suite
      app.kubernetes.io/part-of: blong-suite
      app.kubernetes.io/version: 1.13.0
resources:
  - blongdeployment.yaml
  - deployments/access.yaml
  - deployments/core.yaml
  - deployments/login.yaml
  - deployments/marine.yaml
  - external-services/db.yaml
  - external-services/mysql.yaml
  - ingresses/blong-suite-test.yaml
  - namespaces/blong-services.yaml
  - namespaces/blong-suite.yaml
  - rbac/auth-review-binding.yaml
  - rbac/auth-review.yaml
  - rbac/blong-operator-role-blong-services.yaml
  - rbac/blong-operator-role.yaml
  - rbac/blong-operator-rolebinding-blong-services.yaml
  - rbac/blong-operator-rolebinding.yaml
  - rbac/jobs-role.yaml
  - rbac/jobs-rolebinding.yaml
  - rbac/service-account.yaml
  - services/access.yaml
  - services/core.yaml
  - services/login.yaml
  - services/marine.yaml
  - services/mysql/claim.yaml
  - services/mysql/credentials-in-suite.yaml
  - services/mysql/credentials.yaml
  - services/mysql/deployment.yaml
  - services/mysql/init-config.yaml
  - services/mysql/service.yaml
  - services/web-http.yaml
