apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: blong-kustomize
    app.kubernetes.io/name: blong-suite
    app.kubernetes.io/part-of: blong-suite
    app.kubernetes.io/version: 1.13.0
    blong.feasible.one/spec-hash: 6e07e1bc576e09ec
  name: core
  namespace: blong-suite
spec:
  ports:
    - name: rpc
      port: 8091
      protocol: TCP
      targetPort: rpc
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: core
    app.kubernetes.io/part-of: blong-suite
  type: ClusterIP
