import {schema} from '@feasibleone/blong';

export default schema(async ({lib: {type}}) => ({
    coral: type.Object({
        coralId: type.Integer(),
        coralName: type.String(),
        familyId: type.Integer(),
        habitatId: type.Optional(type.Integer()),
        coralType: type.Optional(type.String({maxLength: 10})),
        maxDepth: type.Optional(type.Integer()),
        colorPattern: type.Optional(type.String()),
        conservationStatus: type.Optional(type.String({maxLength: 2})),
        isEndangered: type.Optional(type.Boolean()),
        discoveryDate: type.Optional(type.String({format: 'date'})),
        coralDescription: type.Optional(type.String()),
        createdAt: type.Optional(type.String({format: 'date-time'})),
        createdBy: type.Optional(type.Integer()),
        updatedAt: type.Optional(type.String({format: 'date-time'})),
        updatedBy: type.Optional(type.Integer()),
        isActive: type.Optional(type.Boolean()),
    }),
    family: type.Object({
        familyId: type.Integer(),
        familyName: type.String(),
        parentFamilyId: type.Optional(type.Integer()),
        order: type.String(),
        class: type.String(),
        familyDescription: type.Optional(type.String()),
        createdAt: type.Optional(type.String({format: 'date-time'})),
        createdBy: type.Optional(type.Integer()),
        updatedAt: type.Optional(type.String({format: 'date-time'})),
        updatedBy: type.Optional(type.Integer()),
        isActive: type.Optional(type.Boolean()),
    }),
    habitat: type.Object({
        habitatId: type.Integer(),
        habitatName: type.String(),
        habitatType: type.String({maxLength: 20}),
        zone: type.String({maxLength: 20}),
        oceanZone: type.String({maxLength: 20}),
        region: type.String(),
        minDepth: type.Integer(),
        maxDepth: type.Integer(),
        waterTempMin: type.Integer(),
        waterTempMax: type.Integer(),
        latitude: type.Number(),
        longitude: type.Number(),
        protectionStatus: type.Boolean(),
        habitatDescription: type.Optional(type.String()),
        createdAt: type.Optional(type.String({format: 'date-time'})),
        createdBy: type.Optional(type.Integer()),
        updatedAt: type.Optional(type.String({format: 'date-time'})),
        updatedBy: type.Optional(type.Integer()),
        isActive: type.Optional(type.Boolean()),
    }),
    species: type.Object({
        speciesId: type.Integer(),
        speciesName: type.String(),
        scientificName: type.String(),
        genus: type.String(),
        species: type.String(),
        familyId: type.Integer(),
        conservationStatus: type.String({maxLength: 2}),
        bodyLength: type.Number(),
        lifespan: type.Optional(type.Integer()),
        diet: type.Optional(type.String({maxLength: 20})),
        isEndangered: type.Optional(type.Boolean()),
        speciesDescription: type.Optional(type.String()),
        createdAt: type.Optional(type.String({format: 'date-time'})),
        createdBy: type.Optional(type.Integer()),
        updatedAt: type.Optional(type.String({format: 'date-time'})),
        updatedBy: type.Optional(type.Integer()),
        isActive: type.Optional(type.Boolean()),
    }),
}));
