apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: blong-kustomize
    app.kubernetes.io/name: blong-operator
    app.kubernetes.io/part-of: blong-operator
    app.kubernetes.io/version: 0.1.0
    blong.feasible.one/spec-hash: 7c25af52c2f34064
  name: blong-operator
  namespace: blong-system
spec:
  ports:
    - name: rpc
      port: 8091
      protocol: TCP
      targetPort: rpc
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: blong-operator
    app.kubernetes.io/part-of: blong-operator
  type: ClusterIP
