name: Build
run-name: Build => ${{ github.event.pull_request.title }}

on:
  pull_request:
    branches: [main]

jobs:
  build:
    permissions:
      contents: read
      packages: write
      security-events: write
      pull-requests: write
    uses: infitx-org/actions/.github/workflows/rush.yaml@main
    with:
      ci-test-jobs: 2
    secrets:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
