/**
 * The generated index block at the top of every memory file.
 *
 * It exists so an agent can orient in ~40 lines instead of reading the file:
 * every entry appears once, grouped by status, in the form
 * `- <ID> · <area> — <title>`. It is derived, never authored, and `check` fails
 * when it drifts from the entries it describes.
 */

import {wrapText} from './memoryFormat.ts';
import {
    INDEX_END,
    INDEX_START,
    KIND_STATUSES,
    SECTION_HEADING,
    type IMemoryEntry,
    type IMemoryStructure,
    type MemoryKind,
} from './memoryTypes.ts';

/** One index bullet, wrapped to the maximum line length. */
function bullet(entry: IMemoryEntry): string[] {
    const area = entry.meta?.area ?? '?';
    return wrapText(`- \`${entry.id}\` · ${area} — ${entry.title}`, '', '  ');
}

/** The index block lines, markers included. */
export function buildIndexLines(
    kind: MemoryKind,
    entries: readonly IMemoryEntry[],
    manualCount = 0,
): string[] {
    const lines: string[] = [
        INDEX_START,
        '<!-- generated by `blong-dev memory index` — do not edit -->',
        '',
    ];

    const groups: Array<[string, IMemoryEntry[]]> = KIND_STATUSES[kind].map(status => [
        status,
        entries.filter(entry => entry.meta?.status === status),
    ]);
    const unparsed = entries.filter(entry => entry.meta === null);

    for (const [status, group] of groups) {
        if (group.length === 0) continue;
        lines.push(`${status} (${group.length})`, '');
        for (const entry of group) lines.push(...bullet(entry));
        lines.push('');
    }

    // Never hide an entry the parser could not read: `check` reports it, and the
    // index says so rather than quietly omitting it.
    if (unparsed.length > 0) {
        lines.push(`unparsed (${unparsed.length}) — no valid meta line, see \`check\``, '');
        for (const entry of unparsed) lines.push(...bullet(entry));
        lines.push('');
    }

    if (kind === 'todo' && manualCount > 0) {
        lines.push(`manual (${manualCount}) — user-owned, listed below, never indexed`, '');
    }

    lines.push(INDEX_END);
    return lines;
}

/** Index lines for a document, deriving the manual count for the todo kind. */
export function indexLinesFor(structure: IMemoryStructure, kind: MemoryKind): string[] {
    const manual = structure.sections.find(section => section.heading === 'Manual');
    // Only the first line of an item: a multi-line item (a fenced example under
    // it) would otherwise be counted once per line.
    const manualCount = manual
        ? manual.other.filter(line => /^- \[ \]\s/.test(line)).length + manual.entries.length
        : 0;
    return buildIndexLines(kind, structure.entries, manualCount);
}

/** Replace (or insert) the index block. Returns the new lines. */
export function withRefreshedIndex(
    lines: readonly string[],
    structure: IMemoryStructure,
    kind: MemoryKind,
): string[] {
    const next = indexLinesFor(structure, kind);
    if (structure.indexRange) {
        const [start, end] = structure.indexRange;
        const updated = [...lines];
        updated.splice(start, end - start + 1, ...next);
        return updated;
    }

    // No block yet: place it after the title and its intro, before the first
    // section, so the file still reads "what is this / what is in it / details".
    const firstSection = structure.sections[0];
    const at = firstSection ? firstSection.start : lines.length;
    const intro = lines.slice(0, at);
    while (intro.length > 0 && intro[intro.length - 1]?.trim() === '') intro.pop();
    const rest = lines.slice(at);
    return [...intro, '', ...next, '', ...rest];
}

/** True when the file's index block is byte-identical to the derived one. */
export function indexIsCurrent(
    lines: readonly string[],
    structure: IMemoryStructure,
    kind: MemoryKind,
): boolean {
    if (!structure.indexRange) return false;
    const [start, end] = structure.indexRange;
    const current = lines.slice(start, end + 1);
    const expected = indexLinesFor(structure, kind);
    return current.join('\n') === expected.join('\n');
}

/** True when the line opens a new section (used to place the index). */
export function isSectionHeading(line: string): boolean {
    return SECTION_HEADING.test(line);
}
