/**
 * Unit tests for the memory-file parser (`memoryParse.ts`).
 *
 * The parser is what lets every edit be a line splice, so these cases pin the
 * line ranges it reports and the fences it must not mistake for structure.
 */

import {test} from 'tap';

import {parseDoc, parseMeta, renderMeta, splitLines} from './memoryParse.ts';

const SOURCE = `# Frictions — core/blong-kukum

<!-- memory:index -->
<!-- generated by \`blong-dev memory index\` — do not edit -->

**open (1)**

- \`F-001\` · core/blong-kukum — first thing
<!-- /memory:index -->

## Open

### F-001 — first thing
_2026-01-01 · core/blong-kukum · open_

Body paragraph.

## Resolved

### F-002 — second thing
_2026-01-02 · cross-cutting · resolved_

Another body.
`;

test('parseDoc reports the title, the index range, sections and entries', async t => {
    const structure = parseDoc(splitLines(SOURCE));

    t.equal(structure.title, 'Frictions — core/blong-kukum', 'H1 text without the marker');
    t.same(structure.indexRange, [2, 8], 'index block range is inclusive of both markers');
    t.same(
        structure.sections.map(section => section.heading),
        ['Open', 'Resolved'],
        'section order',
    );
    t.equal(structure.sections[0]?.start, 10, 'Open starts at its heading');
    t.equal(structure.sections[0]?.end, 15, 'Open ends at its last content line');
    t.equal(structure.sections[1]?.start, 17, 'Resolved heading line');

    t.same(
        structure.entries.map(entry => [entry.id, entry.section, entry.start, entry.end]),
        [
            ['F-001', 'Open', 12, 15],
            ['F-002', 'Resolved', 19, 22],
        ],
        'entries carry their line range and section',
    );
    t.same(structure.entries[0]?.meta, {date: '2026-01-01', area: 'core/blong-kukum', status: 'open'}, 'meta');
    t.same(structure.entries[0]?.body, ['Body paragraph.'], 'body excludes the meta line and blanks');
    t.same(structure.entries[1]?.body, ['Another body.'], 'second body');
    t.end();
});

test('parseDoc ignores headings inside a fenced code block', async t => {
    const structure = parseDoc(
        splitLines(['# Todo', '', '```md', '## Not a section', '### T-001 — not an entry', '```', '', '## Open', ''].join('\n')),
    );
    t.same(structure.sections.map(section => section.heading), ['Open'], 'only the real section');
    t.equal(structure.entries.length, 0, 'and no entries');
    t.end();
});

test('parseMeta accepts the canonical line and rejects everything else', async t => {
    t.same(parseMeta('_2026-01-01 · core/x · open_'), {date: '2026-01-01', area: 'core/x', status: 'open'}, 'canonical');
    t.equal(parseMeta('_2026-01-01 · core/x_'), null, 'two fields');
    t.equal(parseMeta('2026-01-01 · core/x · open'), null, 'no italics');
    t.equal(parseMeta('_not-a-date · core/x · open_'), null, 'date shape');
    t.equal(parseMeta('a paragraph'), null, 'prose');
    t.equal(parseMeta('_2026-01-01 · core/x · open_ and more'), null, 'text after the meta line');
    t.end();
});

test('renderMeta round-trips through parseMeta', async t => {
    const meta = {date: '2026-09-15', area: 'tools/blong-dev', status: 'resolved'};
    t.same(parseMeta(renderMeta(meta)), meta, 'round trip');
    t.end();
});
